### PR TITLE
Imagine

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | yes - ImaginePlugin
| Fixed tickets     | #2945, #1948
| Refs tickets      | #1644, #3121, #703, #577, #418
| License           | MIT
| Changelog updated | yes

## Description
Add, install and configure the LiipImagineBundle. **Deprecate all plugins**.

### CODE REVIEW

**Comment by cmfcmf** [comment]
How would a module add more filter sets?

**Comment by craigh** [comment]
> How would a module add more filter sets?

it would not. I don't know how to make that happen. ideas?

**Comment by craigh** [comment]
> How would a module add more filter sets?

of course, it can always use _runtime options_ (http://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#runtime-options)

**Comment by cmfcmf** [comment]
> of course, it can always use runtime options

Right, I forgot those. This could work then 😄

**Pull request merged**
