### PR TITLE
update Hooks to Symfony 5

### PR DESCRIPTION
**Pull request by craigh**
This includes temporary example files in `/App` and modifies the following files in order to achieve those:

These files should be changed back when testing is complete.
 - composer.json
 - config/services.yaml
 - config/routes/annotations.yaml

These files should be removed:
 - src/Controller/TestHookController.php (the template file for this controller is _not included_)
 - src/HookEvent/*
 - src/HookListener/*
 - src/Form/*

| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | YES
| Fixed tickets     | @see linked issues
| Refs tickets      | @see linked issues
| License           | MIT
| Changelog updated | yes

## Todos

- [x] ~Tests - for HookLocator, Connection?~
- [x] Documentation
- [x] Changelog
- [x] Code
  - [x] add ConnectionPostChangeEvent
  - [x] fix installer to include new code (check HookBundleInstaller and CoreInstallerListener)
  - [x] update HooksListener to add link to new UI
  - [x] adapt ModuleInstallListener to new code (what happens if code not in an extension?)
  - [x] move example code from App to docs

### CODE REVIEW

**Comment by craigh** [comment]
current status after https://github.com/zikula/core/pull/4593/commits/817e262d2f991b777e5bb88d871365ab4d5a1042

Screen Shot 2021-02-08 at 6 11 38 PM

**Comment by craigh** [comment]
current template also:

```twig
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Applications/MAMP/htdocs/core.git/src/Controller/TestHookController.php'|file_link(0) }}">src/Controller/TestHookController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Applications/MAMP/htdocs/core.git/templates/test_hook/index.html.twig'|file_link(0) }}">templates/test_hook/index.html.twig</a></code></li>
    </ul>
</div>
    <div>
        <h3>Display Hook Responses:</h3>
        {% set displayEvent = dispatchEvent('App\\Hook\\AppDisplayHookEvent', ['my-ID']) %}
        <p>Display hook dispatched then responses are looped and formatted individually into list items:</p>
        <ul>
            {% for response in displayEvent.responses %}
                <li>HI {{ response }}</li>
            {% endfor %}
        </ul>
        <p>Or the same object simply output</p>
        <p>{{ displayEvent }}</p>
    </div>
    <div>
        <h3>Filter Hook Demo</h3>
        {% set text = 'Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky.' %}
        <p>ORIGINAL TEXT = {{ text }}</p>
        <p>FILTERED TEXT = {{ text|dispatchFilterHookEvent('App\\Hook\\AppFilterHookEvent') }}</p>
    </div>
```

**Comment by Guite** [comment]
`% set displayEvent = dispatchEvent('App\\Hook\\AppDisplayHookEvent', ['my-ID']) %}`

What is this array argument able to carry?

**Comment by craigh** [comment]
see https://github.com/zikula/core/blob/main/src/Zikula/CoreBundle/Twig/Runtime/EventDispatcherRuntime.php#L36

**Comment by craigh** [comment]
Screen Shot 2021-02-10 at 4 00 12 PM

**Comment by craigh** [comment]
```twig
    <div>
        <h3>Display Hook Responses:</h3>
        {% set displayEvent = dispatchEvent('App\\HookEvent\\AppDisplayHookEvent', ['my-ID']) %}
        <p>Display hook dispatched then responses are looped and formatted individually into list items:</p>
        <ul>
            {% for response in displayEvent.responses %}
                <li>HI {{ response }}</li>
            {% endfor %}
        </ul>
        <p>Or the same object simply output</p>
        <p>{{ displayEvent }}</p>
    </div>
    <div>
        <h3>Filter Hook Demo</h3>
        {% set text = 'Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky.' %}
        <p>ORIGINAL TEXT = {{ text }}</p>
        <p>FILTERED TEXT = {{ text|dispatchFilterHookEvent('App\\HookEvent\\AppFilterHookEvent') }}</p>
    </div>
    <div>
        <h3>Form Demo</h3>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_row(form.name) }}
        {% for template in preHook.templates %}
            {{ include(template.filename, template.vars, true, true) }}
        {% endfor %}
        {{ form_row(form.save) }}
        {{ form_end(form) }}
    </div>
```

**Comment by Guite** [comment]
Some suggestions for shorter names:

- `PreHandleRequestFormHookEvent` could become `FormAmendEvent` or `FormModificationEvent` or similar (as it is dispatched directly after a form is built and allows for modifying it)
- `PostValidationFormHookEvent` could become `FormPostSubmitEvent` or `FormPostValidationEvent` (not sure yet whether we should dispatch it also for invalid form submissions or not)

**Comment by craigh** [comment]
current UI:

Screen Shot 2021-02-16 at 6 39 28 PM

**Comment by Guite** [comment]
UI-related question: as soon as some extensions contribute hooks and listeners the table becomes very large I guess. Hence, maybe we should consider some filters for dynamically hide/show columns and rows? Maybe using a list of checkboxes by bundle. So you can unselect everything except for example News and EZComments. Whenever a bundle is selected/unselected, all corresponding rows and columns are shown/hidden. WDYT?

**Comment by craigh** [comment]
Yes, the UI table could become large. Filtering is an idea to consider. But "by bundle" is not going to always work because applications could be entirely bundle-less.

**Comment by Guite** [comment]
> But "by bundle" is not going to always work because applications could be entirely bundle-less.

Maybe by namespace then?

**Review by Guite — APPROVED** [review]
Two questions:

1. How is the connection entity's table going to be created if the hook bundle will be used in a non-Zikula environment? Flex recipe? Auto detection? (of course this is outside of this PR).

2. Do you have considered a place in UI where the user can see the summary/information about a hook (like described in #4398)? Didn't find it.

Otherwise go for it :+1: :+1: :cake: :1st_place_medal:

**Comment by craigh** [comment]
> How is the connection entity's table going to be created if the hook bundle will be used in a non-Zikula environment? Flex recipe? Auto detection? (of course this is outside of this PR).

There is a new schema:create command in this PR that _could_ be used, but ultimately, that would be the problem of the developer implementing it..

> Do you have considered a place in UI where the user can see the summary/information about a hook (like described in #4398)? Didn't find it.

There is a list under the UI with all the HookEvents and HookEventListeners.

**Pull request merged**
