### PR TITLE
Js translation

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #2601, #2487
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
Add BazingaJsTranslationBundle and add zikula type translation with tests
## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

**Comment by craigh** [comment]
I'm not sure this is complete, but it is worth considering for 1.4.5 even as is.

**Comment by craigh** [comment]
this includes the swift mailer update

**Comment by craigh** [comment]
One thing I don't like is that this method sets the arguments without the '%' signs. And so this differs from the php method.

**Comment by Guite** [comment]
This is awesome :+1: 

Please add an example to the Markdown file for how a module should implement this: How must the catalogue be named? Does it need to be initialised somehow? Any JS files to include? Etc.

**Comment by Guite** [comment]
> how a module should implement

module or theme of course :-)

**Comment by Guite** [comment]
Also the following files contain (commented) calls of `Zikula.__` which might be converted:

- system/CategoriesModule/Resources/public/js/categories_admin_edit.js
- system/CategoriesModule/Resources/public/js/categories_admin_view.js
- system/PageLockModule/Resources/public/js/PageLock.js
- system/RoutesModule/Resources/public/js/ZikulaRoutesModule.Validation.js
- system/ZAuthModule/Resources/public/js/Zikula.ZAuth.PassMeter.js

**Comment by Guite** [comment]
> Also the following files contain (commented) calls of Zikula.__ which might be converted:

Did that in https://github.com/zikula/core/pull/3338/commits/902240ec25cd96ef4a6609a1997f50fee2c6d104

**Comment by craigh** [comment]
> This is awesome

thanks!

> Please add an example ...

> I'm not sure this is complete

😆

**Pull request merged**
