### PR TITLE
Add current language detection to route plugin

### PR DESCRIPTION
**Pull request by Kaik**
Set _locale if not present to current language ($view->language)

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2472 
| Refs tickets      | #2472 
| License           | MIT
| Doc PR            |
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
@cmfcmf ?

**Comment by Kaik** [comment]
please wait with this I need to confirm it's still needed

**Comment by Guite** [comment]
@Kaik how about this one?

**Comment by craigh** [comment]
please see [my comment](https://github.com/zikula/core/issues/2472#issuecomment-109737757) on the original ticket. I believe this fix is unneeded.

**Pull request closed without merging**
