### PR TITLE
Update INSTALL-1.4.0.md

### PR DESCRIPTION
**Pull request by rallek**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2277
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | [yes/no]

Adding a remark for uploading files

### CODE REVIEW

**Comment by craigh** [comment]
please add the [PR header temple](https://github.com/zikula/core/blob/1.4/CONTRIBUTING.md)

**Comment by craigh** [comment]
should the upgrading document also include this information?

**Comment by rallek** [comment]
I hope I did right. I do not have experience with changes at the core :-)

**Comment by craigh** [comment]
no. you want to add it to the PR (up above in this thread below "Adding a remark for uploading files") See other closed PRs for example.

**Comment by craigh** [comment]
e.g. https://github.com/zikula/core/pull/2300

**Comment by rallek** [comment]
mmh, I have no idea how to do. I made everything with github, not local.  In which file I have to add this table?

remember: I am not able to code, I am testing ;-)

**Comment by craigh** [comment]
none. no code.

you just edit the first post in the thread. it should look like https://github.com/zikula/core/pull/2300 when you are done.

**Comment by rallek** [comment]
oh, that easy?

**Comment by craigh** [comment]
> oh, that easy?

:smile: 

> should the upgrading document also include this information?

**Comment by rallek** [comment]
Upgrading is in preparation. Let us see if I am able to add this here...

**Comment by rallek** [comment]
Did it :-)

**Pull request merged**
