### PR TITLE
Upgrade to Bootstrap 4

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | yes
| Deprecations?     | no
| Fixed tickets     | #3530
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
As part of this PR Bootstrap is upgraded from version 3 to version 4. Also we are simplifying it's integration into the core.

Particularly we completely remove the less/sass meta layer for these main reasons:

1. Much more complexity than needed: basically we use Bootstrap, but we don't extend or amend it significantly.
   - We want to stay close to the standard.
   - The scss files are really many and we just don't want to fiddle around with them.
2. More update pain: the component repo does not include any sass/scss sources atm (for similar reasons).
3. Bootstrap 4 does not contain glyph icons anymore (which we usually removed in favour of font awesome). Instead they [recommend using FA now](https://getbootstrap.com/docs/4.3/extend/icons/#preferred), too.

So from now on we just treat Bootstrap as what it is - a vendor component - and work with it instead on it.

If somebody wants to further customize things he can still do it. We provide the possibility to use a custom bootstrap css path for that. But Zikula does not have to provide the "source" experience of the whole BS package ootb.

This PR also removes the "zikula.stylesheet.bootstrap-font-awesome.path" because there is no need to have this in one file then anymore. Asset combination can do this instead if desired.

## Todos
- [x] Check that latest [BS release](https://github.com/twbs/bootstrap/releases) is available in [component repo](https://github.com/components/bootstrap/releases) (created PR: https://github.com/components/bootstrap/pull/59)
- [x] Completely remove the less/sass meta layer
- [x] Remove the "zikula.stylesheet.bootstrap-font-awesome.path"
- [x] We have some simple cosmetic overrides in our bootstrap_variables. Review them and either remove them or possibly put them into core.css for the moment.
- [x] Check if [modal fix for mmenu](https://github.com/zikula/core/blob/master/src/system/AdminModule/Resources/public/js/ZikulaAdminModule.Modal.Fix.js) is still needed.
- [x] Adapt `FormExtensionBundle` to Symfony's Bootstrap 4 Form Theme
- [x] Upgrade bundle and module templates
- [x] Remove Andreas08 and SeaBreeze themes
- [x] Upgrade Bootstrap theme
- [x] Extend Bootstrap theme to support not only cerulean multiple themes from https://bootswatch.com/ - at the end these are only [different css files](https://github.com/thomaspark/bootswatch/tree/v4.4.1/dist) and they [support composer](https://github.com/thomaspark/bootswatch/blob/master/composer.json)
- [x] Provide an additional Bootstrap theme variable (checkbox option) to allow users switching between Bootswatch styles using a dropdown. Unsure whether it's worth the effort (maybe something for later).

### CODE REVIEW

**Comment by Guite** [comment]
Removal of old stuff:

Screenshot_20200105_162113


Style switcher:

Screenshot_20200105_162136

**Comment by Guite** [comment]
"Sketchy":

Screenshot_20200105_174105

**Comment by craigh** [comment]
I am getting this error:
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.bundle.min.js.map, line 0) http://127.0.0.1/core.git/src/web/bootstrap/js/bootstrap.bundle.min.js.map

**Comment by Guite** [comment]
> I am getting this error:
> 
> > [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.bundle.min.js.map, line 0) http://127.0.0.1/core.git/src/web/bootstrap/js/bootstrap.bundle.min.js.map

Will be fixed here: https://github.com/components/bootstrap/pull/59/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Pull request merged**
