### PR TITLE
[WIP] new workflow system

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | **yes (raises minimum PHP version to 5.5.9)**
| Deprecations?     | no
| Fixed tickets     | #2423 
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Todos

- [x] Setup a `WorkflowBundle` collecting our extensions
- [x] Build a small example module and play around
- [x] Load workflows from different locations
- [x] Add a management UI / editor
  - [x] Evaluate tools
  - [x] Build a standalone editor
  - [x] Two modes: petri net vs. state machine!
  - [x] Incorporate it into the bundle
- [x] Update generator implementation https://github.com/Guite/MostGenerator/issues/973
- [x] Editor improvements
  - [x] Dynamic setting of workflow type
  - [x] Dynamic setting of marking store type and marking store field
  - [x] Dynamic setting of supported entities
  - [x] Add further constraints
    - [x] State machine mode: does not allow to have a subject in many places
    - [x] Petri net mode: a subject must be in all places before a transition is enabled
- [x] Complete docs
- [x] Check if raising minimum PHP version can be avoided

### CODE REVIEW

**Comment by Guite** [comment]
@craigh This is ready except the increased PHP version requirement.

**Comment by craigh** [comment]
travis is still failing the build

**Comment by Guite** [comment]
But for an independent reason. It is also failing in `1.4`.

**Comment by craigh** [comment]
please rebase

**Comment by craigh** [comment]
I did the rebase online

**Pull request merged**
