### PR TITLE
Add symfony/flex dependency

### PR DESCRIPTION
**Pull request by craigh**
This removes `zikula/core` dependency on `symfony/symfony` and instead requires needed components. Additionally, it adds dependency on `symfony/flex`. Flex is not useful in this state however except for core development (which seems minimal). Once this is merged, the distribution would need to be updated as well to ensure the flex dependency is used there. When this is done, real-world (downline) development starting with the distribution becomes possible using flex.

| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | #4352, #3601, #3438, #3962
| License           | MIT
| Changelog updated | yes

Using flex has become increasingly needed with the premier of the `symfony/ux` initiative which relies on webpack-encore as well. I think we could implement webpack-encore without using it to "install" our primary front-end dependencies (bootstrap, jquery, etc). but instead use it initially only for the `core.css` file (and maybe the jQuery config file) and then, allow it to be used for downline development.

### CODE REVIEW

**Review by Guite — DISMISSED** [review]
I really like this change.
But I vote for adding all Symfony components for 3.x to ensure BC.

Background: until #3438  is done the core can not ensure that no conflicts may occur because of extensions requiring additional Symfony components (in possibly too old or too new version). Hence, extensions need to rely on the core providing the entire Symfony ecosysystem. Of course this has limits (e.g. we should not include all possible notifier packages), but the most important components need to be kept available even if the core does not use them internally. One example for this is the messenger component.

**Comment by craigh** [comment]
@Guite, I have added the remaining components AFAIK except those noted in the updated changelog. Not noted there, these are also not added:
 - symfony/inflector (deprecated)
 - symfony/semaphore (experimental)
 - symfony/uid (experimental)

I believe semaphore and uid were added in 5.2 anyway, so there is no reason to include them. inflector is to be replaced by the string component.

I've worked hard to ensure BC. I believe I've got all as needed. Please review again.

**Review by Guite — APPROVED** [review]
Nice!

Adding uid soon will become useful though, but it is not urgent :smile:

**Comment by craigh** [comment]
@Guite any further thoughts or concerns here? If not, I will merge this later when I have time. Looks like I will do it locally to deal with the conflicts.

**Comment by Guite** [comment]
No objections.

**Pull request closed without merging**
