### PR TITLE
use grid classes for smaller viewport

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2722
| Refs tickets      | 
| License           | MIT
| Doc PR            | 
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
@Guite I'm just looking into this. but I see you did not create a "topic" branch. this makes checking out the PR much more difficult. In the future, please create topic branches if you intend to PR.

**Comment by craigh** [comment]
before
after

**Comment by craigh** [comment]
I'm not sure which I prefer. I think I remember a previous discussion about this a couple years ago. may @phaidon was involved? I can't be sure, it has been a long time ago. If the field label is extra long, the current method may be better since the break would occur sooner? maybe @Kaik has an opinion or @cmfcmf or @shefik or @rallek

**Comment by rallek** [comment]
for me both cases are fine. I do not have enough experience to judge this. Might be while testing the current 1.4.2dev I do get an idea of this.

**Comment by Kaik** [comment]
I prefer second option - might be, a step sooner(sm), but first one is too soon I think...

**Comment by craigh** [comment]
@Guite maybe `col-sm-*` would be better? (I really don't know)

**Comment by craigh** [comment]
here is one of the commits I was thinking about. I guess it wasn't so long ago :wink: 
https://github.com/zikula/core/pull/2399

**Pull request merged**
