### PR TITLE
Remove AsseticBundle

### PR DESCRIPTION
**Pull request by Kaik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | [no]
| New feature?      | [yes/no]
| BC breaks?        | no well...
| Deprecations?     | no
| Fixed tickets     |  #2685
| Refs tickets      |  #2685
| License           | MIT
| Changelog updated | [yes]

## Description
I have read #2685 and I think we should remove it before anyone will start using it before it's too late.

### CODE REVIEW

**Comment by Guite** [comment]
:+1:

**Comment by craigh** [comment]
I have the same reservations still. what if someone is using it?

**Comment by Kaik** [comment]
I really doubt that there is anyone who is using it and know what is doing. Even if there is a person or two who are using it on purpose and they know what it does, well they should be able to install it again. Anyone else should use zasset.

**Comment by craigh** [comment]
please add changelog in the BC Break area.

**Pull request merged**
