### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by craigh**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/qBByOL).

### CODE REVIEW

**Comment by craigh** [comment]
@Guite you merged changes that failed StyleCI. This PR corrects that. In the future, please correct them prior to merging. ;-)

**Comment by Guite** [comment]
> changes that failed StyleCI

I didn't change the files affected by this PR.

**Comment by craigh** [comment]
> it looks like StyleCI changed something which seems not wanted by us

hmm. something is wrong still tho.

**Comment by Guite** [comment]
https://styleci.readme.io/docs/change-log#section-12082017-august-updates

**Pull request closed without merging**
