### PR TITLE
migrated legacy forms context menu plugin to jQuery, refs #1214

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | #1214 
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by cmfcmf** [comment]
:+1:

**Comment by craigh** [comment]
would third party modules (Content?) be utilizing `Form.contextMenu.commandScript` ?

**Comment by Guite** [comment]
Yes, I even tested using Content ;-)

**Comment by Guite** [comment]
Technically speaking: since they only call `{formcontextmenuxy}` plugins they keep working.

**Comment by craigh** [comment]
awesome :+1:

**Comment by espaan** [comment]
That would mean that contextmenu in #1214 is done ?

**Comment by Guite** [comment]
Yes

**Comment by espaan** [comment]
That could probably be ported to 13x even. If not in the regular branch then at least local to avoid having to use prototype

**Pull request merged**
