### PR TITLE
Namespace change

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | yes
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
This pull request moves the `Zikula\Bridge\`, `Zikula\Core\` and `Zikula\Common\` namespaces into `Zikula\Bundle\CoreBundle\` and `Zikula\ExtensionModule\`.

Classes are moved into sub namespaces where appropriate. For example installer-related classes now live in `Zikula\ExtensionModule\Installer\` and interfaces as well as base classes for common modules are now placed in `Zikula\ExtensionModule\ModuleInterface\`.

The `Zikula\Composer` namespace is moved into the `build` folder, since it is only required as part of composer execution.

### CODE REVIEW

**Comment by Guite** [comment]
FYI: Travis builds are failing because value addon modules (like Profile etc.) are not converted yet. I have this prepared but am waiting with this until the PR is accepted.

**Comment by craigh** [comment]
removed SortableColumns already
https://github.com/zikula/core/commit/bd529bcf884d6755c415f9c69b817b4a3e8f56bb

Go ahead and make changes to va modules in order that this will build properly before merging

**Comment by Guite** [comment]
@craigh ready for review

**Comment by craigh** [comment]
I'm having second thoughts about that last comment. If you want to wait and discuss late tonight, we can do that.

**Comment by craigh** [comment]
> Summary:
- `AbstractModule`: ExtensionsModule root
- `AbstractCoreModule`: ExtensionsModule root
- `AbstractBundle`: CoreBundle root
- `Helper/BundleSchemaHelper`: `CoreBundle/Helper`
- `PersistedBundleHandler`: rename to `CoreBundle/Helper/PersistedBundleHelper`
- `MetaData`: `CoreBundle/Composer`
- `Scanner`: `CoreBundle/Composer`

**Comment by Guite** [comment]
@craigh ready for review

**Comment by craigh** [comment]
👍

**Pull request merged**
