### PR TITLE
Convert system and themes to PSR-4

### PR DESCRIPTION
**Pull request by craigh**
Convert all system modules and all system themes to PSR-4. maintain BC.

## REQUIRES COMPOSER UPDATE !!!

| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | yes*
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | #2424
| License           | MIT
| Doc PR            | -
| Changelog updated | yes

* deprecated items are only a result of namespace changes and a BC layer has been added to compensate.

### CODE REVIEW

**Comment by craigh** [comment]
I think this is ready but would really appreciate some additional testing. @Guite @phaidon @cmfcmf @Kaik

**Comment by craigh** [comment]
refs #2424

**Comment by Kaik** [comment]
I was away for some time now I hope to be able to come back to this soon I need few more days and I will do all the tests and check all the new stuff.

**Comment by craigh** [comment]
> I think this is ready but would really appreciate some additional testing.

wow, was I wrong. :8ball: :boat: 

but now, I think it really is ready, but nobody tests with me. :cry: :sob:

**Comment by craigh** [comment]
Will be merging this Sunday afternoon (EDT) if there are no objections. @Guite @phaidon @cmfcmf @Kaik

**Comment by Guite** [comment]
I just tested a new installation on my local machine which worked fine. Afterwards I clicked a bit through administration and changed several settings. This worked flawlessly as well.

So :+1: from me - and thank your for all this work!

**Comment by cmfcmf** [comment]
Thank you @craigh.

**Pull request merged**
