### PR TITLE
use symfony token manager for ajax

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | yes
| BC breaks?        | no?
| Deprecations?     | yes
| Fixed tickets     | -
| Refs tickets      | #3206
| License           | MIT
| Changelog updated | [yes/no]

## Description
A few sentences describing the overall goals of the pull request's commits.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

### CODE REVIEW

**Comment by craigh** [comment]
this is the basic idea. I guess the `\Zikula\Core\Token\CsrfTokenHandler` class would be refactored to use symfony's also

**Comment by Guite** [comment]
Looks good. Just wondering whether all existing ajax POST requests will fail if they do not explicitly send the token variable in their payload though :thinking:

**Comment by Guite** [comment]
Changelog?

**Comment by craigh** [comment]
> Changelog?

yes, stuff to do yet, I wanted your opinion on the basic idea

**Pull request closed without merging**
