### PR TITLE
Fix admin footer / header

### PR DESCRIPTION
**Pull request by cmfcmf**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | ---
| Refs tickets      | ---
| License           | MIT
| Changelog updated | no

Call the Controllers instead of simply including the templates, as they might (and do!) define different template variables.

### CODE REVIEW

**Comment by craigh** [comment]
seems ok? I guess I don;t really understand. this was @Kaik 's thing.

**Comment by Kaik** [comment]
This is ok you could as well use ```{{ adminHeader() }} ``` Twig tag.
I think this will not solve #3031

**Comment by craigh** [comment]
ah yes. For consistency, let's use `{{ adminHeader() }}` and `{{ adminFooter() }}` ?

**Comment by craigh** [comment]
@Guite this is from your refactoring. Did you do similar methods in other places or did you use the twig functions?

**Comment by Kaik** [comment]
This will be changed anyway to fix #3031. I need to rewrite this to use AdminController::categorymenuAction. I will redirect all smarty tags to use controller refactored by @Guite these support legacy. Then add ```deprecated``` to all functions and files that need to be removed when smarty is removed.

**Comment by craigh** [comment]
@Kaik are you saying close this PR and you will fix in a new one?

**Comment by Kaik** [comment]
yes please

**Comment by cmfcmf** [comment]
The same issues still exists.

**Pull request merged**
