### PR TITLE
added composer file validation, fixed #2669

### LINKED ISSUE #2669: Validate extension composer files
now that the Core-2.0 spec is utilizing the composer file for extension meta data, we must validate the file/data before the extension can be added.

ExtensionLibrary does something similar for its manifest.

look into https://github.com/justinrainbow/json-schema

https://github.com/zikula/ExtensionLibrary/tree/master/Schema

https://github.com/zikula/ExtensionLibrary/blob/master/Manager/RemoteJsonManager.php#L140-L162

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #2669 
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

### CODE REVIEW

**Comment by craigh** [comment]
will psr-0 modules validate? They should in 1.4

**Comment by Guite** [comment]
updated schema readding support for plugins and psr-0 components

**Comment by Guite** [comment]
validation is now also enabled for themes

**Comment by craigh** [comment]
`zikula-plugin` is not needed. There is no such thing and the system cannot handle that anyway. All plugins are legacy.

**Comment by craigh** [comment]
this is a cool PR though 👍

**Comment by craigh** [comment]
oops - merging problems.

**Comment by Guite** [comment]
:(

**Comment by Guite** [comment]
Rebased

**Comment by craigh** [comment]
nice 👍

**Pull request merged**
