### PR TITLE
remove the Zikula\Core\Api\AbstractApi class. 

### PR DESCRIPTION
**Pull request by craigh**
It is a BC Break. But since it was just introduced and there are very unlikely any modules using it yet, I believe it to be safe to remove.

| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | YES
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2494
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | YES

@cmfcmf @Guite @phaidon @Kaik please vote :+1: :-1:  (others welcome also of course)

### CODE REVIEW

**Comment by Guite** [comment]
What is the replacement?

I have already 4 modules using it.
Michael just started with the 1.4 version of Eternizer https://github.com/zikula-modules/Eternizer/ which also uses it now.

**Comment by Guite** [comment]
Just saw that the new `getLinks` service can be used as replacement.
So personally I am fine with this change :+1: 

@portugao could you wait with the Eternizer release until 1.4.1 is there? The change is a rather small one.

**Comment by Portugao** [comment]
Yes.

**Comment by craigh** [comment]
Replacements: yes, the LinkContainer and getLinks service are intended replacements for the link Api in <=1.4.0. Api classes are not required at all but of course could still be used and identified as a service instead of extending a base class. This would be the preference. refs #1950 

another option of course would be to simply `@deprecate` the entire class and leave it there until 2.0 but I don't want to encourage its usage, so I thought removing it was the better solution.

**Comment by Portugao** [comment]
:-1: 
Would prefere to @deprecate the class and leave it until 2.0.

**Comment by craigh** [comment]
> There is enough to understand with 1.4.

that is why I am suggesting eliminating it. :smile: don't learn the 1.4 way and have to learn the 1.4.1/2.0 way again. just jump straight to the latter.

**Comment by Kaik** [comment]
:+1: I think that 1.4.1 should introduce much more BC so we can have quicker transition, at least at this kind of "easy level" as getLinks. You can still use Api class for your own things just this "internal stuff" is moved. Fine with me. :+1:

**Comment by craigh** [comment]
@Kaik I'm not sure you understand. This "new" AbstractApi was introduced in Core-1.4 but will NOT be used in Core-2.0. (It probably shouldn't have been introduced - my fault). So this is just to remove it. The FC-layer with the new getLInks service is implemented already and will be the way it will work in Core-2.0. I hope that is clearer.

**Comment by Kaik** [comment]
@craigh I thought that AbstractApi will become what Api is... in general so other application/module can communicate with "this module". Maybe not that big like google api but kind of similar exposing some default functionality between modules. I do not have problem with any of ways anyway as I was using Api only for links in my modules.

**Comment by Guite** [comment]
@Kaik Api classes are going to be replaced by Symfony services: http://symfony.com/doc/current/book/service_container.html
About communication: by tagging services http://symfony.com/doc/current/book/service_container.html#tags event listeners can interact with them.

**Comment by craigh** [comment]
> I thought that AbstractApi will become what Api is...

yes, modules are allowed to publish a 'public' Api if they wish, but I don't want the core to provide an Abstract to base this on. The providing module will need to declare the Api a symfony service and inject whatever services it requires there.

**Comment by Kaik** [comment]
> but I don't want the core to provide an Abstract to base this on

Well for me it is ok. Like I said I'm using it only for getlinks. There is nothing else to put in it since symfony/doctrine everything what used to be there is now in repository

**Comment by craigh** [comment]
So it looks like we have 3 :+1: and 1 :-1: 

@cmfcmf ? @phaidon ?

**Comment by cmfcmf** [comment]
Yes, remove it please.

**Comment by Guite** [comment]
https://github.com/Guite/MostGenerator/commit/c2447deffb6ac2cd561c6cb3595b083f32ccec10

**Pull request merged**
