### PR TITLE
Fixed description

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The remaining StyleCI patch should now be safe to apply.

**Comment by GrahamCampbell** [comment]
It can send you a pull request if you click the "Send fix PR" button on the most recent analysis. ;)

**Comment by craigh** [comment]
yes. thanks I'll take a look.

**Comment by craigh** [comment]
@GrahamCampbell - it is removing default values of method arguments for some reason. Is this a feature or a bug? Any way to disable?

**Comment by GrahamCampbell** [comment]
> it is removing default values of method arguments for some reason. Is this a feature or a bug? Any way to disable?

It's because they are impossible default values because they are followed by a value without a default. Do you see?

**Comment by GrahamCampbell** [comment]
eg, the following default value is impossible:

```php
function test($foo = null, $bar) {}
```

**Comment by craigh** [comment]
thanks. I see now. A lot of old code... grrr.

**Pull request merged**
