### PR TITLE
Search - Correcting Conditional Statement

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Changelog updated | [yes/no]

## Description

Correcting the conditional statement to parse active modules to search.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

### CODE REVIEW

**Comment by craigh** [comment]
please add a changelog entry.

**Comment by craigh** [comment]
how did you notice this problem? I'd like to understand better since there is no associated ticket. What caused the issue?

**Comment by shefik** [comment]
I came across the bug while executing a search with my own custom modules. I noticed that all module's search helper code were being run. Troubleshooting the code revealed the problem with the conditional statement being incorrect.

So, to duplicate the issue, you will need to install a module that has search capabilities. You won't be able to encounter the bug with just the Zikula core alone, since it doesn't have search modules to test with.

**Comment by shefik** [comment]
Would this really need a changelog entry? It's not a new feature. It's just a regular bug fix for something that was already broken.

**Comment by craigh** [comment]
> You won't be able to encounter the bug with just the Zikula core alone, since it doesn't have search modules to test with.

The core allows searching of users, so there is one module.

My concern then (because last I checked it worked with the core) is if something may be wrong elsewhere then (in Users for example). 

> Would this really need a changelog entry

yes please.

**Comment by shefik** [comment]
Yes, the Users module is indeed searchable. But, I was able to more easily and quickly spot the issue by having multiple searchable modules installed, and I noticed that I kept seeing results from all the modules.

**Comment by craigh** [comment]
OK. Can you please test whether Users still functions as expected with your fix? 🙇

**Comment by shefik** [comment]
Yes, Users still works.

**Comment by craigh** [comment]
> Yes, Users still works.

great! just update the changelog and we can merge this then.

**Comment by shefik** [comment]
Changelog has been updated.

**Comment by craigh** [comment]
thank you @shefik

**Pull request merged**
