### PR TITLE
Overhauled and improved translation extraction and handling

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #4012
| Refs tickets      | #2425, #4057
| License           | MIT
| Changelog updated | yes

## Description
This PR basically includes the following amendments:

- Remove JMSTranslationBundle entirely
- Install and enable php-translation/symfony-bundle instead
- Configure it's functionality and create two configurations (one for core and one for extensions)
- Add a new GitHub actions workflow for running the extractor every 2 days and adding missing translations as a pull request
- Add annotations (`@Ignore` and `@Translate`) where needed
- Remove more unrequired translator calls in form types
- Move some remaining form creations from controllers into form types
- Remove unrequired translator calls in flashes
- Add docs for translator and extractor handling (will be finished in #4057)
- Utilise the "Edit in Place" functionality
- Utilise the "WebUI" functionality
- Change the way we use translation domains (not equal to the bundle name anymore, but a context for translators, like for example `mail`, `messages`, `navigation`, `validators` and `admin`)
- Extend `LocaleApi` to support lists without and with regions (e.g. `de_DE`)
- Centralise locale-related parameters and reuse for different bundles
- Extend `LocaleApi` to reflect auto-discovery of new/removed locales in configuration (using new `LocaleConfigHelper`)
- Implement dynamic configuration handling for translation settings (required e.g. for web ui) (using new `TranslationConfigHelper`)
- Add missing extractor for form type alerts
- Add missing extractor for form type input groups
- Add missing extractors for KnpMenuBundle
- Add missing extractor for JMSI18nRoutingBundle

### CODE REVIEW

**Comment by craigh** [comment]
according to https://symfony.com/doc/master/bundles/KnpMenuBundle/i18n.html

> The KnpMenuBundle translates all menu items by default

I don't think we've been assuming this and so have been injecting translator.  might be worth testing.

**Comment by Guite** [comment]
Please still inject the translator into knp menus. The php-translation extractor does not support it yet otherwise.

**Comment by Guite** [comment]
If I cope with implementing one I'll let you know. For now, keep on injecting translator.

**Comment by craigh** [comment]
please add extraction to travis job when this is ready

**Comment by Guite** [comment]
> please add extraction to travis job when this is ready

I've already setup an independent Github workflow: https://github.com/zikula/core/blob/translation/.github/workflows/update-translations.yml
This is going to create pull requests for new/missing translations.

**Comment by craigh** [comment]
> If I cope with implementing one I'll let you know. 

if you don't, I will eventually.

**Pull request merged**
