### PR TITLE
make table determination more error-prone

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2284 
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
the problem may simply be that the `NotNull` validation needs to occur before the custom Validator in the installer checking for a PDO connection.

**Comment by craigh** [comment]
apparently, one cannot control the order of the validators.

**Comment by craigh** [comment]
How about just checking for a null value before proceeding? instead of looking for errors?

**Comment by Guite** [comment]
Added a check for empty credentials (password is not checked since people could use an empty password on purpose, e.g. for testing).

**Comment by craigh** [comment]
is the first stuff you added still needed then?

**Comment by Guite** [comment]
I would keep it, because it makes the functionality a bit more robust.

**Comment by cmfcmf** [comment]
@craigh  It is possible to control the order of the validator, see http://symfony.com/doc/current/book/validation.html#validation-groups and the next paragraphs.

**Comment by craigh** [comment]
I briefly looked at that before and it didn't seem related, but I will take another look I guess.

**Pull request merged**
