### PR TITLE
Update bootstrap.tpl

### PR DESCRIPTION
**Pull request by rallek**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | [no]
Adding the hamburger symbol for mobile view

### CODE REVIEW

**Comment by Kaik** [comment]
Hmm I do not know if this is good idea to add 'hamburger' menu by default. Not all menu's should be collapse able. We would need to add setting in block to turn it off/on.

**Comment by rallek** [comment]
@Kaik You are right. Turning on/off would be great. But unfortunally  I do not have enough skills. Is it a solution just to add a second hamburger-bootstrap.tpl?

**Comment by Kaik** [comment]
>Is it a solution just to add a second hamburger-bootstrap.tpl

As long as there is a way to chose this template in block modify it will be good temporary solution :)

**Comment by rallek** [comment]
I will redo these things. I tested localy the way to have a second template. While doing this I found some other smal issues.
I will do a new PR with two layouts and some small improvements later. First I have to bring the fork to my computer :-)

**Pull request closed without merging**
