### PR TITLE
use original service name instead of alias

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | #2790 
| License           | MIT
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
why do you feel this renaming is important?

**Comment by craigh** [comment]
> why do you feel this renaming is important?

I see it is relevant to #2790.

I think some real-usage testing is in order with this PR since the last time caused problems (although I can't see why this should cause issues). So please actually test an install and general usage with this PR and report.

**Comment by Guite** [comment]
I tested this already. This PR does not change any behaviour, it just uses the original service name to reduce dependencies to our custom `DoctrinePass` class.

**Comment by craigh** [comment]
> I tested this already.

:+1: merge it then.

**Pull request merged**
