### PR TITLE
override symfony native RoutingExtension for cases where route is not…

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | [yes/no]
| New feature?      | [yes/no]
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Changelog updated | [yes/no]

## Description
A few sentences describing the overall goals of the pull request's commits.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

… available. @cmfcmf

### CODE REVIEW

**Comment by craigh** [comment]
@cmfcmf here is an idea

**Comment by cmfcmf** [comment]
I disagree with this. I think the default behaviour of these functions should remain.

**Comment by craigh** [comment]
> I disagree with this. I think the default behaviour of these functions should remain.

solution then is to use 

`{% if modAvailable('MyCustomModule') %}{{ path('mycustommodule_controller_method') }}{% endif %}`

for all routes that could possibly not be available at time of upgrade, etc.

ping @shefik

**Comment by craigh** [comment]
see https://github.com/zikula/core/commit/18233ac856620dce54112bff92a29c127daf4cdd

**Comment by shefik** [comment]
@craigh I did that already, wrapping the route in the conditional statement. But, it still resulted in the same error.

**Comment by craigh** [comment]
interesting.

**Comment by craigh** [comment]
I've tested this and it works as I expected.

How I tested it:

I added this code to the top of `src/system/ExtensionsModule/Resources/views/Module/viewModuleList.html.twig`

    Profile: {{ modAvailable('ZikulaProfileModule') }} : {{ isBundle('ZikulaProfileModule') }}
    {% if modAvailable('ZikulaProfileModule') %}{{ path('zikulaprofilemodule_user_index') }}{% endif %}

the `isBundle()` function is a temporary plugin/function I added just to check if the kernel has the bundle loaded. It only does this `return $this->container->get('kernel')->isBundle($name);` and the results were always the same as `modAvailable()`

When profile was uninstalled entirely, it looked like
`Profile: :`

when installed and active it looked like
`Profile: 1 : 1 /core.git/src/profile/`

when installed and inactive it looked like
`Profile: :`

when installed but requiring upgrade it looked like
screen shot 2016-08-27 at 8 56 13 am
`Profile: 1 : 1 /core.git/src/profile/`

and the upgrade completed and worked as expected.

@shefik wrote:
> I did that already, wrapping the route in the conditional statement. But, it still resulted in the same error.

I cannot explain the behavior of your module(s). Every test I have run works as I expect.

**Pull request closed without merging**
