### PR TITLE
Prevent a potential timeout, if the site is using a load balancer.

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
Mrs must pass all checks before merging. please correct the StyleCI issue.

**Comment by craigh** [comment]
I don't really understand this well, so more information would be appreciated. But, that being said, as I understand it, this would add 14 seconds to this stage of the installation. From a Users perspective this is a really long time and I don't think that would be the best solution. Is there any way to *detect* if a load balancing system is in place? And if so, make adjustments then? This seems like a hacky solution - maybe we can address the real problem, if we can know it.

**Comment by shefik** [comment]
@craigh Fixed.

**Comment by shefik** [comment]
The main issue is with a host such as Rackspace, which has a load balancer on their Cloud Sites service. If there is a long AJAX execution, it does not matter if the AJAX timeout is set longer. Eventually, the load balancer will timeout, since it is not sending a response back to the browser. So, this pull request periodically sends a header, to indicate that it should not timeout the load balancer.

**Comment by craigh** [comment]
@Guite thoughts?

**Comment by craigh** [comment]
@shefik PR needs reset.

**Comment by craigh** [comment]
@Guite @cmfcmf thoughts on this?

**Comment by Guite** [comment]
No idea nor experience with this.

**Comment by cmfcmf** [comment]
same.

If this is really required, it could be improved by querying the time with http://php.net/manual/de/function.microtime.php and sending a header if a second has passed - thus removing the hard sleep.

**Comment by shefik** [comment]
@cmfcmf I think recommending to use microtome is a good idea. I'll modify my code to test the results, and update the pull request accordingly.

**Comment by craigh** [comment]
ping @shefik

**Comment by craigh** [comment]
ping @shefik I need this fixed if you want it included in Core-1.4.2, otherwise it waits for 1.4.3

**Comment by shefik** [comment]
Ok, looking into it.

**Comment by cmfcmf** [comment]
Closing due to lack of response.

**Pull request closed without merging**
