### PR TITLE
fix #3166

### LINKED ISSUE #3166: Upgrade 1.4.1 to 1.4.3 failed
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.5.30

### Expected behavior
after installing modules everything should work as before

### Actual behavior
I do get an error:
````
 Unable to transform value for property path "[shorturls]": Expected a Boolean.
500 Internal Server Error - TransformationFailedException
1 linked Exception:

    TransformationFailedException » 

[2/2] TransformationFailedException: Unable to transform value for property path "[shorturls]": Expected a Boolean.  + 
````

### Steps to reproduce

* follow upgrade instructtion
* create a backup of webserver files and database
* setup a clone of your site with the beackup data and test if it runs (``www/Zikula_Core-1.4.1.bak`` for http://bak.mysite.de)
* instead of deleting all files I created a parallel folder with fresh zikula download in ``www.Zikula_Core-1.4.3``
* copy both config files (I am using always cp -r ... on my comand line for copy to keep the right permissions)
* copy theme (mine is based on the 1.4.1 boostrap theme and running well in my clone)
* copy userdata
* run upgrade on my backup site
* login with admin and see the admin panel, test frontpage and see the wellcome message, great!
* copy all modules from bakup to new modules folder e.g. New, Content, Scribite, Captcha, MedaModule,...
* call admin Extension list and see all modules inactive (fine)
* activating them one by one but not MediaModule (not shure for issues, want to upgrade soon)
* next I tried to go to main settings to create the start module, site name and so on. Here I got the error message

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3166
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
Fix #3166

### CODE REVIEW

**Comment by craigh** [comment]
@rallek if you want to try to edit your local files to include these changes, you should be able to upgrade the setting module from your extensions list and see if the problem is fixed. let me know if you can and will and the result.

**Comment by rallek** [comment]
Upgrade is not offered after changing the file at the server (cache is cleared)

**Comment by Guite** [comment]
@rallek I think @craigh meant that you should change the files before running the core upgrade,

**Comment by rallek** [comment]
will do now

**Pull request merged**
