### PR TITLE
Make Bootstrap theme site default

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
Make Bootstrap theme site default (new features added, blocks and permissions adjusted specific to theme). Improved compatibility of zikula-specific bootstrap overrides with respect to navbars. Provide method for customizing Bootstrap path in Core-2.0 themes

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

**Comment by craigh** [comment]
This is how it looks after initial install.

screen shot 2016-03-24 at 12 40 45 pm

**Comment by craigh** [comment]
screen shot 2016-03-25 at 4 55 33 pm

New page post-install.

**Comment by craigh** [comment]
@Guite @cmfcmf @rallek @shefik I would appreciate your testing this and :+1: :-1: :question: 

I would like it to be part of 1.4.2, so please do so ASAP. thanks.

**Comment by rallek** [comment]
as I am not using composer I did it as following: download from ci the latest build (155), download the branch ``boostrap-theme`` and copied it over the 155 ci build. I also added our (incomplete) german translation.
Installation via browser went fine. Some sentences are translated to german also :-)

The new layout is great! A very good starting point for my own upcomming theme! Thanks a lot!

Result :+1:

**Comment by rallek** [comment]
You should increase the boostrap theme version number to 2.0.0 instead of 1.0.0 because there has been another version off this theme in 1.4.1

**Comment by craigh** [comment]
Thank you for testing this ralf!

**Comment by craigh** [comment]
> A very good starting point for my own upcomming theme!

@rallek be sure to see https://github.com/zikula/core/blob/bootstrap-theme/src/docs/Admin/CustomBootstrapCss.md

**Pull request merged**
