### PR TITLE
removed obsolete Doctrine extension listeners and service aliases, fixed #1982

### LINKED ISSUE #1982: Remove old Doctrine extensions implementation
Follow-up from #1711 - the old implementation should be removed as soon as the fallback is not required anymore.

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #1982 
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

### CODE REVIEW

**Comment by craigh** [comment]
nice. can this be merged into 1.5 or only master?

**Comment by Guite** [comment]
I'd suggest only master.

**Comment by craigh** [comment]
> I'd suggest only master.

why? does it change any behavior?

**Comment by Guite** [comment]
As it removes a bunch of services it potentially breaks existing modules which use not the stof service names yet but the old ones which delegate(d) to stof.

**Comment by Guite** [comment]
```
        $types = ['Blameable', 'Loggable', 'SoftDeleteable', 'Uploadable', 'Sluggable', 'Timestampable', 'Translatable', 'Tree', 'Sortable'];
        foreach ($types as $type) {
            $container->setAlias(strtolower("doctrine_extensions.listener.$type"), 'stof_doctrine_extensions.listener.' . strtolower($type));
        }
```

**Comment by craigh** [comment]
be sure to note required changes in the 1.5 changelog then. merge when ready

**Pull request merged**
