### PR TITLE
fix issue where routes may conflict with directory structure

### LINKED ISSUE #2215: Unable to access Themes admin
These URLs are not accessible:

/themes/admin
/themes/admin/view

### PR DESCRIPTION
**Pull request by craigh**
Add checks for such in customizing area and upgrade. closes #2215

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2215
| Refs tickets      | -
| License           | MIT
| Doc PR            | included
| Changelog updated | n/a

### CODE REVIEW

**Comment by shefik** [comment]
@craigh What happens if the URL is changed via the translatable POT files? Is there a check there too?

**Comment by Guite** [comment]
My guess is that no URLs should be present in the pot files, but they should be assigned as argument to the gettext call.

**Comment by shefik** [comment]
Okay, because the URLs are currently in POT files at the moment.

**Comment by Guite** [comment]
Created a separate issue at #2224 for this-

**Comment by shefik** [comment]
@craigh I tested this commit. It throws an exception "InvalidArgumentException", instead of redirecting the user back to the form to correct the issue, when a URL has the same name of an existing directory.

**Comment by craigh** [comment]
> Okay, because the URLs are currently in POT files at the moment.

where?

**Comment by craigh** [comment]
> It throws an exception

yes. this is the expected behavior

**Comment by shefik** [comment]
@craigh Shouldn't the form be shown again to make it user-friendly? In the POT file search for "theme". That is used as the URL.

**Comment by craigh** [comment]
> Shouldn't the form be shown again to make it user-friendly?

probably, but I just copied the way the API handles other invalid entries, which is an exception. This was done throughout the core. Wrongly IMO, but done and so I kept it consistent.

**Pull request merged**
