### PR TITLE
use variable for session name and use setting from SecurityCenterModule

### LINKED ISSUE #2150: Session cookie name is not working
securitycenter/session settings/Session cookie name:

If I change the session cookie name to e.g. _rksid the cookie will be still named _zsid

### PR DESCRIPTION
**Pull request by craigh**
closes #2150 

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2150
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | n/a

### CODE REVIEW

**Comment by cmfcmf** [comment]
I thought you were going to use the dynamic config dumper? :-(

**Comment by craigh** [comment]
I sort of am :smile: In the installer refactor, I abstracted most of it to the YamlDumper class and I'm using that to write directly to `custom_parameters.yml`

do you think I should use the dynamic settings instead?

**Comment by cmfcmf** [comment]
> do you think I should use the dynamic settings instead?

Well why not?

**Comment by craigh** [comment]
> Well why not?

this seemed simpler ;-)

**Comment by cmfcmf** [comment]
> this seemed simpler ;-)

Well then we could just dump everything directly to `custom_parametery.yml` and remove the `dynamic_config.yml`, no?

**Comment by craigh** [comment]
I guess so. why are we doing it with the dynamic config then?

**Comment by cmfcmf** [comment]
> I guess so. why are we doing it with the dynamic config then?

I don't remember :disappointed:

**Pull request merged**
