### PR TITLE
encode parameters before writing to ensure values are 'safe'

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2376
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
@shefik - this should fix the password problem.

@Guite or @cmfcmf - I would like your opinion on this. I don't know anything about base64 encoding, so don't know if that is a concern. The encoding isn't for anything other than making the string 'safe' so I doubt there is reason for concern, but wanted to know if you we ok with this before merging.

**Comment by Guite** [comment]
Looks fine imho.

**Comment by shefik** [comment]
@craigh I tested the code, and it fails with the following error:

```
Notice: unserialize(): Error at offset 2 of 6 bytes in /Users/shefik/Documents/SourceTree/Gorilla/shefik/Sources/MacroSyntax/src/lib/Zikula/Core/Doctrine/Entity/ExtensionVarEntity.php on line 81
```

The installation process successfully executes the AJAX. When I click the "Finish" button, the error is thrown.

I used this as the admin password:

```
ATB4n!uWh@f$*Se
```

**Comment by Guite** [comment]
Maybe this relates to the admin email address which is saved as modvar, too.

**Comment by craigh** [comment]
@shefik - please post the entire trace.

**Comment by craigh** [comment]
I cannot reproduce the error using password `ATB4n!uWh@f$*Se`. I suspect that you entered a faulty email address or possibly did not use the correct branch?

I'm merging this.

**Comment by shefik** [comment]
@craigh Confirmed. It is working correctly for me now. Installed Zikula 1.4.0 build 515.

**Pull request merged**
