### PR TITLE
upgrade to Symfony 5.2.0-BETA2 (or better)

### PR DESCRIPTION
**Pull request by craigh**
upgrade to Symfony 5.2.0-BETA2 (or better)

### CODE REVIEW

**Review by Guite — APPROVED** [review]
Travis is failing.

**Comment by craigh** [comment]
> Travis is failing.

sadly, this is due to a vendor error: https://github.com/willdurand/BazingaJsTranslationBundle/issues/291

**Comment by craigh** [comment]
> sadly, this is due to a vendor error: willdurand/BazingaJsTranslationBundle#291

Actually, it is due to changes in symfony config:

https://github.com/symfony/symfony/issues/38615

**Comment by craigh** [comment]
Symfony now saws it is not Symfony's fault

> It looks like the bundle relies on the constructor signature from Symfony 3 where the $options argument was the fourth one. This has changed in 4.0 where the $defaultLocale was added in between (meaning that $options is now the fifth argument).

so, if BazingaJsTranslationBundle doesn't get fixed then we have a problem

**Comment by craigh** [comment]
@Guite this could be merged now if you agree

**Review by Guite — APPROVED** [review]

**Pull request merged**
