### PR TITLE
Correcting Module Domain

### PR DESCRIPTION
**Pull request by shefik**
This corrects the loading of the module domain, where it was pointing to an incorrect path.

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | https://github.com/zikula/core/issues/2407
| Refs tickets      | https://github.com/zikula-modules/DizkusModule/issues/274
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by cmfcmf** [comment]
I'm not sure if I understand correctly. What is wrong with `zikuladizkusmodule` as translation domain? (sure, it is different from what it was for 1.3.x modules, but as it will only affect newly created 1.4.x modules, this isn't so much of a problem).

**Comment by shefik** [comment]
@cmfcmf I updated the code to remove "module_". I have no issue with the domain just being ```zikuladizkusmodule```. If this is a change for 1.4.x, I'm fine with that.

Note: this pull request still fixes the other issue, where the files were not being loaded correctly.

**Comment by craigh** [comment]
nice work tracking this down and fixing it. I think this needs a changelog entry because the method is changed from 1.3. Also - it would be extra good if it could be documented somewhere else also. maybe the wiki? I can't remember if there are other wiki docs on translating.

**Comment by craigh** [comment]
so three places I think:
1. https://github.com/zikula/core/blob/1.4/src/docs/en/dev/UPGRADE-1.4.0.md
2. https://github.com/zikula/core/wiki/Translating
3. changelog

**Comment by craigh** [comment]
ping @shefik - can you take care of these other items so we can merge this?

**Comment by shefik** [comment]
This wiki has been updated:

```
https://github.com/zikula/core/wiki/Translating
```

**Comment by shefik** [comment]
UPGRADE-1.4.0.md has been updated.

**Comment by Guite** [comment]
Thank you @shefik

**Pull request merged**
