### PR TITLE
user block fixed #2891

### LINKED ISSUE #2891: Missing link to userblock
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.3.10
| PHP Version       | 5.6

The userblock is shown on frontend (migrated from 1.2.9) but no link in /index.php?module=User&type=user&func=main to edit the entries of this block

### PR DESCRIPTION
**Pull request by Portugao**
typo was the reason

### CODE REVIEW

**Comment by cmfcmf** [comment]
Thank you @Portugao!

**Comment by cmfcmf** [comment]
Ignore the Style errors - it is configured for the 1.4 branch and can be ignored for 1.3. Could you also add a CHANGELOG.md entry?

**Comment by Portugao** [comment]
I try.

**Comment by Portugao** [comment]
@cmfcmf 
How to get the changelog entry into this pull request?

**Comment by craigh** [comment]
make changes
push changes to your user-block branch

**Comment by Portugao** [comment]
Ok. Thanks, @craigh .

**Comment by Portugao** [comment]
Done!

**Comment by craigh** [comment]
nice work @Portugao  thanks!

**Pull request merged**
