### PR TITLE
Correcting error "Failed to load resource...412 (Precondition Failed)"

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | https://github.com/zikula/core/pull/2388
| License           | MIT
| Doc PR            | -
| Changelog updated | no

/cc @craigh

### CODE REVIEW

**Comment by craigh** [comment]
this fixes the problem?

**Comment by shefik** [comment]
I don't see the error anymore in the console.

**Comment by cmfcmf** [comment]
But why does it fix the problem?

**Comment by shefik** [comment]
I'm not quite sure. But, when that that option is set, there is no error. Also, the error only seemed to occur when Zikula is installed in a subdirectory. There was no error when it's installed at the document root.

**Comment by craigh** [comment]
> But why does it fix the problem?

that's what I was wondering :stuck_out_tongue_closed_eyes: 

But @shefik is right, it seems to have fixed the problem. Not only is the console clear, but the functionality is there (I works).

**Comment by craigh** [comment]
@shefik please add a comment in the code explaining why it appears to be in debug mode and then we'll merge it.

**Comment by shefik** [comment]
Without that option being set, "debug" is "undefined" by default (according to the Webshim docs). So, maybe it needs to be set?

**Comment by craigh** [comment]
setting it to false however brings the error back

`$.webshims.setOptions('debug', false);` doesn't work.

**Comment by shefik** [comment]
Correct, I did try as FALSE already. Only setting to TRUE works.

**Comment by shefik** [comment]
I think it might be a bug with the webshim library. So, after this particular commit is merged, I'll open up a ticket at the webshim project, so the developer can take a look himself. The "debug" option shouldn't need to be set.

**Comment by shefik** [comment]
@craigh Comment has been added to the code.

**Comment by craigh** [comment]
@shefik - thank you for continuing to work on this and fix it!

**Comment by shefik** [comment]
You're welcome.

**Pull request merged**
