### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by Guite**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/87GYwZ).

### CODE REVIEW

**Comment by Guite** [comment]
@craigh does that really make sense?

**Comment by craigh** [comment]
> does that really make sense?

not to me. many of these classes are not in the global namespace so prefixing them with a slash doesn't seem right.

@cmfcmf ideas?

**Comment by cmfcmf** [comment]
> @cmfcmf ideas?

You could also adjust all the classes to include the full namespace.

**Comment by craigh** [comment]
I changed some config at StyleCI and disabled the FqCN issue.

**Pull request closed without merging**
