### PR TITLE
Force short array syntax.

### PR DESCRIPTION
**Pull request by cmfcmf**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

Force Short Array Notation in StyleCI.

### CODE REVIEW

**Comment by cmfcmf** [comment]
This needs to wait for #2851 of course :smiley:

**Comment by craigh** [comment]
😢 It appears you have not rebased correctly.

**Comment by craigh** [comment]
it may be simpler to close this and create a second?

**Comment by cmfcmf** [comment]
I was trying to use the GitHub Client, but it failed me. :cry: 
I will properly rebase tomorrow :smiley:

**Pull request closed without merging**
