### PR TITLE
Disabling CSRF Protection

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | https://github.com/zikula/core/issues/3831
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
Disabling CSRF protection.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

### CODE REVIEW

**Comment by Guite** [comment]
Please remove the option `'csrf_token_id'   => 'zikulasearchmodule_search',` which is not required anymore.

**Comment by Guite** [comment]
Did you test that this actually works?

**Comment by shefik** [comment]
@Guite Yes, it works. `csrf_token_id` has been removed now.

**Comment by Guite** [comment]
Looks fine for me now.

@craigh ?

**Comment by Guite** [comment]
@shefik please rebase to target latest `1.5` branch. Thank you!

**Comment by shefik** [comment]
Closing this pull request. Use this instead - https://github.com/zikula/core/pull/3845

**Pull request closed without merging**
