### PR TITLE
Changelog entry for #2364

### PR DESCRIPTION
**Pull request by nmpetkov**

### CODE REVIEW

**Comment by Guite** [comment]
Please add to https://github.com/zikula/core/blob/1.4/CHANGELOG-1.3.md since this feature has been added to 1.3.10.

**Comment by craigh** [comment]
I think it was already added to the 1.3 branch?

**Comment by craigh** [comment]
oops - no, not yet

**Comment by nmpetkov** [comment]
Now I'm discovering, that there is two changelog files for branch 1.3.

**Comment by craigh** [comment]
I guess so, yes - maybe https://github.com/zikula/core/blob/1.4/CHANGELOG-1.3.md could be deleted? @Guite ?

**Comment by Guite** [comment]
I doubt that... guess that it was introduced to get it more like Symfony does it: https://github.com/symfony/symfony/

**Comment by craigh** [comment]
Yes

**Pull request merged**
