### PR TITLE
hook fixes refs #3745

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3745 
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

ping @Guite @Kaik is this sufficient to fix the problem?

### CODE REVIEW

**Comment by Guite** [comment]
@Kaik meant to review "all core modules". This PR only addresses Users. Either the other modules are missing or there were no errors there :wink:

**Comment by craigh** [comment]
> Either the other modules are missing or there were no errors there

there are no other calls to `notifyDisplayHooks()` in any other templates.

**Comment by Guite** [comment]
How about introducing them for (at least) Blocks and Groups?

**Comment by Kaik** [comment]
Hi, sorry guys I'm really busy... I dive into Dizkus hooks so much I forgot to do this... Hooks are not really used in core... and looks like only UsersModule and BlockModule uses hooks - both do not have proper display_view call for object. UsersModule because there is no - user view page and BlockModule - hmm should be in block template.

**Comment by craigh** [comment]
> How about introducing them for (at least) Blocks and Groups?

> hmm should be in block template

the html block has this hook call which I missed before but needs no adjustment:

https://github.com/zikula/core/blob/6ecc9936856be64eb603efd160c46e23c82494a5/src/system/BlocksModule/Resources/views/Block/html_modify.html.twig#L2

> only UsersModule and BlockModule uses hooks - both do not have proper display_view call for object

I would say that they are implemented properly. Please explain what you mean. 

> UsersModule because there is no - user view page

and there shouldn't be. That is handled by Profile.

@Guite if you desire further additions, please create a FR ticket and schedule it for 2.1.0. #3745 is only a bug fix.

**Pull request merged**
