### PR TITLE
Fix #2971

### LINKED ISSUE #2971: Zikula 1.4.3 (105) Fails to Install
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior

The install page should display.

### Actual behavior

Warning: require(/vendor/composer/../../../src/lib/i18n/ZGettextFunctions.php): failed to open stream: No such file or directory in /vendor/composer/autoload_real.php on line 66

### Steps to reproduce

Download Zikula 1.4.3 build 105. You will see the error at initial page load.

### PR DESCRIPTION
**Pull request by cmfcmf**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #2971
| Refs tickets      | ---
| License           | MIT
| Changelog updated | no

This is untested. I suggest to merge it and see if the CI builds work :-)

### CODE REVIEW

**Comment by craigh** [comment]
is this a future-proof solution? in other words, is it based on the ci server's PHP version or something else? If we eventually require PHP > 5.6 or something can these fixers be removed?

**Comment by cmfcmf** [comment]
> is this a future-proof solution?

If Composer changes their file formats again, we will need to update once again, just as we had to when they introduced `autoload_psr4.php`: https://github.com/zikula/core/commit/bd3c1fdb982917ddc3100ad75e1d7f4eeddb649e

> in other words, is it based on the ci server's PHP version or something else? If we eventually require PHP > 5.6 or something can these fixers be removed?

No. This has nothing to do with the PHP version but rather with our builds who have to manually remove all `src` prefixes in Composer generated files. Now Composer recently added a new file, `autoload_static.php`, which we need to add to our list of files to fix.

It is _entirely unrelated_ that Composer only includes this file for PHP >= 5.6 as a performance improvement.

**Comment by craigh** [comment]
thanks for the extra info.

I'm good with merging this. 👍

**Comment by Guite** [comment]
Like it :+1:

**Pull request merged**
