### PR TITLE
Reenabled support for legacy hooks

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | https://github.com/zikula-modules/Scribite/issues/165
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
This is exactly the code that #3608 and #3618 removed in favor of better solutions. This cannot be re-added because it requires a ContainerBuilder which is not allowed any more. We need a different solution

**Comment by Guite** [comment]
Added #3684 
But honestly I don't see why the old code can't be kept in 1.x.

**Comment by craigh** [comment]
reopened so the branch doesn't get deleted.

I'm looking in to it.

**Comment by craigh** [comment]
@Guite please see https://github.com/zikula/core/commit/1aae6f400a482ac9073902451c7b3c0a2f34c561

**Pull request closed without merging**
