### PR TITLE
Adding Webshim to add polyfill for HTML5 form validation in browsers

### PR DESCRIPTION
**Pull request by shefik**
Adding Webshim to add polyfill for HTML5 form validation in browsers, such as adding support in Safari on Mac.

This corrects the installer.

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | https://github.com/zikula/core/issues/2321
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by shefik** [comment]
Note: webshim currently not available to install via composer, so it has been added to the directory "/javascript" instead.

**Comment by craigh** [comment]
this is a very 'heavy' commit. 313 files? seems like a lot for what I think it is doing. can you explain more about the benefits of including this? what does it do?

**Comment by shefik** [comment]
@craigh In this particular case, a browser such as Safari on Mac does not fully support the "required" attribute via HTML5 validation. Therefore, forms are able to be submitted without proper client validation. Webshim provides a variety of polyfills. For the installer, only the polyfills for "forms" is loaded. Even though only the polyfill for "forms" is needed for the installer, all other shims from the library are provided in the core, if developers need them for loading other polyfills, as desired.

Once this is pull request merged, other core modules that have forms can make similar use of proper HTML5 validation. So, it's not only a matter of supporting the "required" attribute cross-browser, but we will be able to properly support HTML5 validation, using attributes such as validation via regex and other valid attributes.

**Comment by craigh** [comment]
:+1:

**Comment by craigh** [comment]
ping @phaidon FYI

**Comment by shefik** [comment]
I opened at ticket at the Webshim project, requesting support to be able to install via composer. In the meantime, the library is located at /javascript/js-webshim.

If a package for composer is made available, the library can be installed to /vendor later on.

https://github.com/aFarkas/webshim/issues/491

**Comment by cmfcmf** [comment]
At least the whole dev folder could have been removed, no? This would probably lower the overall size a lot.

**Comment by shefik** [comment]
@cmfcmf Then, the same can be said about all other libraries where we add both the minified and unminified versions. I would think we need to provide both. (But, have sites only link to the minified version for production use.)

**Pull request merged**
