### PR TITLE
Fix stylesheet

### PR DESCRIPTION
**Pull request by cmfcmf**

### CODE REVIEW

**Comment by craigh** [comment]
I think I might prefer a `file_exists` check in the AbstractModule

**Comment by craigh** [comment]
merge = bad. rebase = good.

**Comment by cmfcmf** [comment]
Thank you :P

Craig Heydenburg <notifications@github.com> schrieb am Do., 17. Dez. 2015
um 15:05 Uhr:

**Comment by cmfcmf** [comment]
> I think I might prefer a file_exists check in the AbstractModule

I was considering the same thing, but went with the exception because it already does the check in `locateResource`.

**Pull request merged**
