### PR TITLE
Adding support for getting the parent class of a bundle

### PR DESCRIPTION
**Pull request by shefik**
Based on the Symfony docs referenced here:

http://symfony.com/doc/current/cookbook/bundles/inheritance.html

| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | https://github.com/zikula/core/issues/2448
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by shefik** [comment]
A listener (such as `module_dispatch.custom_classname`) can't be used anymore for this type of class override. Instead, use inheritance to override, by creating a new YAML file at this example module path:

`modules/Example/Resources/config/bundle.yml`

The file contents should be based on this sample:

```
zikulaexamplemodule:
    parent: ZikulaParentModule
```

Then, in your controller, instead of extending `\Zikula_AbstractController`, extend a class within that parent module. The parent module's class should be extend `\Zikula_AbstractController` as normal.

**Comment by shefik** [comment]
The code I committed works for one module to directly extend another module. However, my need is to have one module directly extend multiple modules. Apparently, this is not supported in Symfony2, because only one bundle can be extended.

http://stackoverflow.com/questions/9109669/how-can-i-extend-a-bundle-more-than-once
http://stackoverflow.com/questions/15428516/symfony2-inheriting-more-than-one-bundle

**Comment by shefik** [comment]
I was able to accomplish what I wanted to do, by simply having one module extend multiple modules as-is. It wasn't necessary to set a parent in Symfony to achieve this. Using this sample code in the child:

```
public function exampleAction(Request $request)
    {
        $response = parent::exampleAction($request);

        // ... do custom stuff
        return $response;
    }
```

However, the code in this pull request is still useful, if anyone needs to extend one module with another module. That functionality was missing in the Zikula core.

**Comment by craigh** [comment]
@shefik - why do we need a 'dynamic' `getParent` method? Why not simply ask the bundle(module) author to declare their own method with the parent? Maybe I'm not understanding the value here.

**Comment by craigh** [comment]
ping @shefik

**Comment by shefik** [comment]
@craigh I am not using the code in this pull request anymore in my own use case, due to the issue I mentioned earlier:

`The code I committed works for one module to directly extend another module. However, my need is to have one module directly extend multiple modules. Apparently, this is not supported in Symfony2, because only one bundle can be extended.`

I am now using a different solution to achieve what I want, which is also described above (pull request not needed).

This pull request can be closed, if you don't think there is any need for this particular code.

**Pull request closed without merging**
