### PR TITLE
UsersModule refactor

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed tickets     | -
| Refs tickets      | #1753 
| License           | MIT
| Changelog updated | yes

## Description
Refactor UserModule. Implement AuthenticationMethodInterface. Add ZAuth module.

### CODE REVIEW

**Comment by craigh** [comment]
ping @Guite - if you do any more refactoring, please avoid the UserModule if possible. I just had to walk through a very painful rebase 😢

**Comment by craigh** [comment]
screen shot 2016-06-19 at 9 21 35 pm 👍 😝

**Comment by Guite** [comment]
@craigh as you changed/removed some JS files, please update https://github.com/zikula/core/blob/users/build.xml#L60 accordingly

**Comment by Guite** [comment]
Probably the InstallerBundle also needs an addition to consider the new modules properly.

**Comment by Guite** [comment]
I added the abc pager in #2907 so you probably need to update this part of the PR.

**Comment by craigh** [comment]
> I added the abc pager in #2907 so you probably need to update this part of the PR.

I had already fixed it 😢 I hope we did it the same...

**Comment by Guite** [comment]
Sure, I just copied it from your PR :-)

**Comment by craigh** [comment]
> Sure, I just copied it from your PR :-)

oh good. 😌

**Comment by craigh** [comment]
@Guite - looks like we're all set 👍

**Comment by craigh** [comment]
screen shot 2016-07-07 at 9 40 40 pm 👍 😝 🎉

**Comment by craigh** [comment]
I intend to merge this branch Sunday 10 July or Monday 11 July unless there are objections.

**Comment by Kaik** [comment]
@craigh I'm just playing whole afternoon with users branch and I have experienced few errors. I have not changed much since plain installation just filled some settings in UsersModule. First error occurred in prod mode during registration I have filled all the fields and when pressed Save button error 500 "Invalid argument hashAlgorithmName" - I have tried both native methods uname and email same error each time.

Then I have switched to dev mode to see output and registration page (both methods ) showed me this error 
screenshot from 2016-07-10 21-34-53

**Comment by Kaik** [comment]
Pending users are present in users module even that error occurred during registration. I will play with it more tomorrow.

**Comment by craigh** [comment]
> Pending users are present in users module even that error occurred during registration. I will play with it more tomorrow.

@Kaik, I would need to know _what error_. Also, when you report a problem, please copy the actual trace here (or to a ticket). A screenshot is nice, but I cannot actually look at the trace data.

**Comment by Kaik** [comment]
>@Kaik, I would need to know what error. Also, when you report a problem, please copy the actual trace here (or to a ticket). A screenshot is nice, but I cannot actually look at the trace data.

Ok now new error trace below: btw there is no minpass setting in usersmodule settings?
```
Exception detected! 
Key "minpass" for array with keys "accountdisplaygraphics, accountitemsperpage, accountitemsperrow, userimg, anonymous, avatarpath, allowgravatars, gravatarimage, itemsperpage, login_displayapproval, login_displaydelete, login_displayinactive, login_displayverify, reg_notifyemail, moderation, reg_autologin, reg_noregreasons, reg_allowreg, reg_Illegaluseragents, reg_Illegaldomains, reg_Illegalusername" does not exist in ZikulaZAuthModule:Authentication:register.html.twig at line 32
500 Internal Server Error - Twig_Error_Runtime

Stack Trace
in vendor/twig/twig/lib/Twig/Template.php at line 509   -
                    $message = sprintf('Impossible to access an attribute ("%s") on a %s variable ("%s")', $item, gettype($object), $object);
                }
                throw new Twig_Error_Runtime($message, -1, $this->getTemplateName());
            }
        }
at Twig_Template ->getAttribute (array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'minpass', array()) 
in app/cache/dev/twig/73/73777f76b8a9a4d67392b59b675c8c9af6231c7e8d28f4b2bbf470d84e852cad.php at line 102   + 
at __TwigTemplate_405b0d2f0480d23011178203c008520d791e04867772aff2fb415bba50147e1f ->doDisplay (array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula', 'assetic' => array('debug' => true, 'vars' => object(ValueContainer), 'use_controller' => true), 'app' => object(AppVariable), 'pagevars' => object(ParameterBag), 'themevars' => object(ParameterBag), 'currentUser' => object(CurrentUserApi)), array()) 
in vendor/twig/twig/lib/Twig/Template.php at line 387   + 
at Twig_Template ->displayWithErrorHandling (array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula', 'assetic' => array('debug' => true, 'vars' => object(ValueContainer), 'use_controller' => true), 'app' => object(AppVariable), 'pagevars' => object(ParameterBag), 'themevars' => object(ParameterBag), 'currentUser' => object(CurrentUserApi)), array()) 
in vendor/twig/twig/lib/Twig/Template.php at line 355   + 
at Twig_Template ->display (array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula')) 
in vendor/twig/twig/lib/Twig/Template.php at line 366   + 
at Twig_Template ->render (array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula')) 
in vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php at line 50   + 
at TwigEngine ->render ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula')) 
in vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php at line 72   + 
at TwigEngine ->render ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula')) 
in vendor/elao/web-profiler-extra-bundle/TwigProfilerEngine.php at line 36   + 
at TwigProfilerEngine ->render ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula')) 
in vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php at line 97   + 
at TwigEngine ->renderResponse ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula'), null) 
in vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php at line 185   + 
at Controller ->render ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'), 'domain' => 'zikula'), null) 
in lib/Zikula/Core/Controller/AbstractController.php at line 98   + 
at AbstractController ->render ('@ZikulaZAuthModule/Authentication/register.html.twig', array('form' => object(FormView), 'modvars' => array('accountdisplaygraphics' => true, 'accountitemsperpage' => '25', 'accountitemsperrow' => '5', 'userimg' => 'images/menu', 'anonymous' => 'Guest', 'avatarpath' => 'images/avatar', 'allowgravatars' => true, 'gravatarimage' => 'gravatar.jpg', 'itemsperpage' => '25', 'login_displayapproval' => true, 'login_displaydelete' => false, 'login_displayinactive' => true, 'login_displayverify' => true, 'reg_notifyemail' => 'contact@kaikmedia.com', 'moderation' => false, 'reg_autologin' => false, 'reg_noregreasons' => 'Sorry! New user registration is currently disabled.', 'reg_allowreg' => true, 'reg_Illegaluseragents' => null, 'reg_Illegaldomains' => null, 'reg_Illegalusername' => 'root, webmaster, admin, administrator, nobody, anonymous, username'))) 
in system/UsersModule/Controller/RegistrationController.php at line 186   + 
at RegistrationController ->registerAction (object(Zikula_Request_Http)) 
at call_user_func_array (array(object(RegistrationController), 'registerAction'), array(object(Zikula_Request_Http))) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   + 
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   + 
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 193   + 
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 22   + 
```

**Pull request merged**
