### PR TITLE
Switching from text field to select, for the options of cache lifetime.

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by cmfcmf** [comment]
This could potentially break custom cache times like 60 seconds, etc. I vote for postponing this to 1.4.1. I generally don't want to see too many more features in 1.4.0, because we basically already are in the release process and have kind of a feature freeze.

**Comment by shefik** [comment]
@cmfcmf I agree with your assessment. But, my attempt was to make it easier for site admins to change cache lifetime, without having to do calculations to determine what the values should be. It's easier to just have a drop-down menu. I fine with postponing to 1.4.1, as long as we re-visit this discussion.

**Comment by shefik** [comment]
Perhaps the select menu can be transformed to have the pre-populated values, but also allow a custom value to be entered.

**Comment by craigh** [comment]
> Perhaps the select menu can be transformed to have the pre-populated values, but also allow a custom value to be entered.

@shefik can you make these adjustments please?

**Pull request closed without merging**
