### PR TITLE
Add ajax-based validation for registration form (refs #2321)

### PR DESCRIPTION
**Pull request by jusuff**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | #2321
| Refs tickets  | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by Guite** [comment]
Great!

Is this ready to merge?

**Comment by jusuff** [comment]
IMHO yes. Just waiting for opinions.

**Comment by shefik** [comment]
Please don't merge this yet. I need a couple days to post my comments and suggestions in further detail.

**Comment by jusuff** [comment]
Ok

**Comment by craigh** [comment]
@jusuff I would like to see the modified in one of two ways please:

1) eliminate the 'check your entries' button entirely and check the related fields on blur of the specified form field

or

2) hide the 'submit' button to begin and move the 'check your entries button to the far left (and color it green) then if the form validates, hide the 'check your entries' button and unhide the 'submit' button

otherwise, I think the functionality is great!

**Comment by jusuff** [comment]
@craigh You're right. I will remove "Check your entries" button and validation can be done on submit. If there are errors - show them. If not - just submit form.

**Comment by shefik** [comment]
@jusuff Instead of using your pull request, I created a new pull request here: https://github.com/zikula/core/pull/2377

Please read the comments I posted at that pull request for more details.

**Comment by craigh** [comment]
closed in favor of #2377

**Pull request closed without merging**
