### PR TITLE
validate UserEntity on registration.

### LINKED ISSUE #3256: User name and email existence checks use zauth tables
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4
| PHP Version       | 5.5

### Expected behavior
A username (or an email address if unique emails are configured) may not be registered twice.

### Actual behavior
User name and email address checking is done using the zauth authentication mapping and verification tables. But existing users are only migrated during their (next) login after ZAuth has been installed. Hence, it is possible to register using an already existing user name if the corresponding user is not contained in the zauth tables yet.

### Steps to reproduce
Try to register using a user name which exists in the user table, but not in mapping table yet.

### Proposal
Either enforce a migration of all users to the mapping and verification tables. Or check user name and email address existence using the users table.

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3256
| Refs tickets      | -
| License           | MIT
| Changelog updated | not yet

## Description
fixes #3256

## To do
 - [ ]  add changelog

### CODE REVIEW

**Comment by craigh** [comment]
Do not merge this yet, I still must check admin creation of users. This should fix the initial problem though.

**Comment by craigh** [comment]
@Guite @rallek can you test this solution before it is merged?

**Comment by Guite** [comment]
I think a changelog entry is adequate.

**Comment by rallek** [comment]
A guest is still able to create a user account with the name of an existing user :-(

**Comment by craigh** [comment]
> Do not merge this yet, I still must check admin creation of users

thanks 🙄

**Comment by Guite** [comment]
sorry I thought it would have been done as you asked for testing :blush:

**Pull request merged**
