### PR TITLE
preview png update

### PR DESCRIPTION
**Pull request by rallek**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | n/a
| Fixed tickets     | no
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

some small change in 0dc8a77a2ecefa42b199a2fdd253408130efc214 are leading to different preview_....png

### CODE REVIEW

**Comment by craigh** [comment]
In the future please put the CONTRIBUTING header directly in the commit message.

**Comment by rallek** [comment]
contributing header is the table?

**Comment by craigh** [comment]
yes

**Comment by craigh** [comment]
like this: https://github.com/zikula/core/commit/0dc8a77a2ecefa42b199a2fdd253408130efc214

**Pull request merged**
