### PR TITLE
Category Tree Bug Fixes

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | #2206
| License           | MIT
| Doc PR            | n/a
| Changelog updated | no

refs #2206

### CODE REVIEW

**Comment by craigh** [comment]
@jusuff @Guite 

If you work on this, please use this as a starting point. You can issue PRs against this PR:

```Shell
git fetch origin
git checkout -b CatTreeBugs origin/CatTreeBugs
git merge 1.4
```

the push your own branch and issue PR against this.

There are still many issues I haven't been able to get to work properly, but this is a start. I will probably work on it slowly as I have time, but either of you will likely be much faster if you find the time to work on it.

**Comment by craigh** [comment]
I need help with the ***COPY*** functionality (which doesn't work at all) and the drak and drop to another parent - which breaks everything.

Also when a node is created the icons are not drawn and images are used instead. This corrects itself on reload though.

**Comment by craigh** [comment]
@Guite how do you feel about removing the 'copy' functionality completely? I tested it in 137 and it doesn't work there for me, so apparently it has been broken for a while, but nobody cares :stuck_out_tongue_winking_eye: It seems redundant to me - we already have functions to create new and create new both into a new parent and next to existing category. I don't see what value 'blind copy' might provide.

**Comment by rallek** [comment]
I have never used this function

**Comment by Guite** [comment]
(Almost) never used it, too.

**Comment by craigh** [comment]
> (Almost) 

so how did it function? how was it different than the other options?

**Comment by Guite** [comment]
I don't remember... I could also have written `Never used it, too.` ;-)

**Comment by jusuff** [comment]
Copy allowed you to copy selected category and all it subnodes. Lets say you had node with European curies names and wanted to create another list with EU countries. You could just copy the first node and remove unnecessary nodes. 
I have no idea where is the issue right now. Will work on Zikula today evening and will check this.

**Comment by craigh** [comment]
**fixed** the dnd issue. Still broken:
 - [ ] copy
 - [ ] redraw of tree graphic elements on dynamic (ajax) insert

**Comment by craigh** [comment]
merging this to make further fixes easier.

**Pull request merged**
