### PR TITLE
Correcting form alignment. Refs. #2283

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
this PR would be better if you could simply hard-reset it back to 28d844e5d6f972f9c7fc23ee8adda9e0e5400552

**Comment by craigh** [comment]
accept the invite to slack and I can help you with that if you need.

**Comment by shefik** [comment]
@craigh I just used the GitHub site directly for that commit. I can make further changes later today, when I am at my development computer.

**Comment by shefik** [comment]
Closing this pull request, since a solution has been addressed via https://github.com/zikula/core/issues/2283

**Pull request closed without merging**
