### PR TITLE
implement fix for Prototype jQuery conflict

### PR DESCRIPTION
**Pull request by craigh**
from http://softec.lu/site/DevelopersCorner/BootstrapPrototypeConflict refs #2238

### CODE REVIEW

**Comment by cmfcmf** [comment]
Well, this disabled Prototype functionality. Older stuff using Prototype might break.

**Comment by craigh** [comment]
working here: http://zikula.org/library/e/awesome-test-module for me

**Comment by espaan** [comment]
The method in prototype was maybe cleaner only only overriding methods that were hiding.

**Comment by espaan** [comment]
That is exactly what I have here as well and it works great

**Comment by craigh** [comment]
@espaan can you check this again. I added a check for undefined. I assume it won't be a problem, but need to make sure.

**Comment by espaan** [comment]
Hi, just tested with your update. Works perfect. Prototype is loaded before jQuery now, so that should works and it does when loading Content for instance that still uses prototype for some stuff.
And also a pure jQuery page in the admin section loads fine without any JS problems.
So :+1:

**Comment by craigh** [comment]
@phaidon - you said you would look at this. I would like to merge this today if possible

@jguille2 - you had a hand in the original commit on this as well. Any opinions on this solution?

@jusuff - any opinions?

**Pull request merged**
