### PR TITLE
reduce cacheClears and fix extension installation

### PR DESCRIPTION
**Pull request by craigh**
Installing one extension (ZikulaMultiHookModule) (`APP_ENV=prod`) clears the cache this many times:

```
[2020-04-19T07:55:01.322110-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.config {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerGFdhU5B"} []
[2020-04-19T07:55:53.634537-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerGFdhU5B"} []
[2020-04-19T07:55:53.637799-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerGFdhU5B"} []
[2020-04-19T07:56:11.863943-04:00] zikula.NOTICE: Extension installation begun {"name":"ZikulaMultiHookModule"} []
[2020-04-19T07:56:12.693501-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:12.694986-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.config {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:12.766703-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: assets {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:12.768253-04:00] zikula.NOTICE: Extension installation complete {"name":"ZikulaMultiHookModule"} []
[2020-04-19T07:56:12.770230-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:30.511066-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.routing {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:30.529533-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:30.603079-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerUisTJK8"} []
[2020-04-19T07:56:47.900512-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerFr4VxlB"} []
[2020-04-19T07:56:47.992273-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.config {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/prod/ContainerFr4VxlB"} []
```

### CODE REVIEW

**Comment by craigh** [comment]
installing by CLI (which defaults to `APP_DEV`)

```
[2020-04-19T12:05:34.450532+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.config {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
[2020-04-19T12:05:36.862275+00:00] zikula.NOTICE: Extension installation begun {"name":"CraigHookTestModule"} []
[2020-04-19T12:05:36.865745+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
[2020-04-19T12:05:36.866136+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.config {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
[2020-04-19T12:05:36.917941+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: assets {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
[2020-04-19T12:05:36.918071+00:00] zikula.NOTICE: Extension installation complete {"name":"CraigHookTestModule"} []
[2020-04-19T12:05:37.109491+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.routing {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
[2020-04-19T12:05:37.726843+00:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Applications/MAMP/htdocs/core.git/var/cache/dev/ContainerLu4DWS0"} []
```

**Comment by Guite** [comment]
LGTM

**Comment by Guite** [comment]
Short observation:

`ExtensionHelper` calls `ExtensionStateHelper`.

`ExtensionStateHelper` also clears the cache [here](https://github.com/zikula/core/blob/master/src/system/ExtensionsModule/Helper/ExtensionStateHelper.php#L101).
So I think that we can remove at least [this call](https://github.com/zikula/core/blob/master/src/system/ExtensionsModule/Helper/ExtensionHelper.php#L141) and [this call](https://github.com/zikula/core/blob/master/src/system/ExtensionsModule/Helper/ExtensionHelper.php#L188) - they happen immediately after `ExtensionStateHelper` was called. We should not remove [this call](https://github.com/zikula/core/blob/master/src/system/ExtensionsModule/Helper/ExtensionHelper.php#L235) though.

**Comment by craigh** [comment]
this is log of installation of Legal module (the installer did NOT run still though)

```
[2020-05-10T15:49:33.700618-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\ExtensionsModule\\Helper\\ExtensionStateHelper::updateState>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:33.702904-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:35.417870-04:00] zikula.NOTICE: Extension installation begun {"name":"ZikulaLegalModule"} []

[2020-05-10T15:49:35.538917-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: assets {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\ThemeModule\\EventListener\\ExtensionInstallationListener::clearCombinedAssetCache>
Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke>
Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners>
Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch>
Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch>
Zikula\\ExtensionsModule\\Helper\\ExtensionHelper::install>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:35.539823-04:00] zikula.NOTICE: Extension installation complete {"name":"ZikulaLegalModule"} []

[2020-05-10T15:49:35.542397-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:37.139624-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony.routing {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\RoutesModule\\Listener\\InstallerListener::extensionPostInstalled>
Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke>
Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners>
Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch>
Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::postInstallAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:37.150847-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\SettingsModule\\Helper\\LocaleConfigHelper::updateConfiguration>
Zikula\\SettingsModule\\Api\\LocaleApi::getSupportedLocales>
Zikula\\RoutesModule\\Helper\\RouteDumperHelper::dumpJsRoutes>
Zikula\\RoutesModule\\Listener\\InstallerListener::updateJsRoutes>
Zikula\\RoutesModule\\Listener\\InstallerListener::extensionPostInstalled>
Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke>
Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners>
Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch>
Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::postInstallAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:37.219220-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\SettingsModule\\Helper\\TranslationConfigHelper::updateConfiguration>
Zikula\\SettingsModule\\Listener\\ExtensionInstallerListener::updateTranslationConfig>
Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke>
Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners>
Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch>
Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::postInstallAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []

[2020-05-10T15:49:38.846302-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/ContainerFpjDo68","trace":
"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear>
Zikula\\SettingsModule\\Helper\\LocaleConfigHelper::updateConfiguration>
Zikula\\SettingsModule\\Api\\LocaleApi::getSupportedLocales>
Zikula\\RoutesModule\\Helper\\RouteDumperHelper::dumpJsRoutes>
Zikula\\RoutesModule\\Listener\\InstallerListener::updateJsRoutes>
Zikula\\RoutesModule\\Listener\\InstallerListener::newRoutesAvail>
Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke>
Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners>
Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch>
Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch>
Zikula\\ExtensionsModule\\Controller\\ExtensionController::listAction>
Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw>
Symfony\\Component\\HttpKernel\\HttpKernel::handle>
Symfony\\Component\\HttpKernel\\Kernel::handle> "} []
```

**Comment by craigh** [comment]
with the hack, it works. The results in the log are interesting:

```
[2020-05-12T07:55:16.696988-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 1 to 7 [] []
[2020-05-12T07:55:16.937711-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: symfony {"containerDir":"/Container87XRh39","trace":"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear(112) >>Zikula\\ExtensionsModule\\Helper\\ExtensionStateHelper::updateState(294) >>Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction(157) >>Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw(79) >>Symfony\\Component\\HttpKernel\\HttpKernel::handle(191) >>Symfony\\Component\\HttpKernel\\Kernel::handle(35) >>"} []
[2020-05-12T07:55:18.125087-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:18.137682-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:21.483514-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:21.496505-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:24.821377-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:24.834185-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:28.137729-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:28.150621-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:31.457195-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:31.470316-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:34.787204-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:34.800017-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:38.048613-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:38.061370-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:41.375365-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:41.388071-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:44.714040-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:44.726559-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:48.029063-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:48.041671-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:51.353834-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:51.366633-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:54.690954-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:54.703855-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:55:58.007788-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:55:58.020487-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-12T07:56:16.156156-04:00] zikula.ERROR: InstallerCollector found Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:56:16.220558-04:00] zikula.NOTICE: Extension installation begun {"name":"ZikulaLegalModule"} []
[2020-05-12T07:56:16.221161-04:00] zikula.ERROR: InstallerCollector found Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-12T07:56:16.447319-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 7 to 3 [] []
[2020-05-12T07:56:16.670232-04:00] zikula.NOTICE: Zikula\Bundle\CoreBundle\CacheClearer: assets {"containerDir":"/ContainerB8Sf588","trace":"Zikula\\Bundle\\CoreBundle\\CacheClearer::clear(88) >>Zikula\\ThemeModule\\EventListener\\ExtensionInstallationListener::clearCombinedAssetCache(117) >>Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener::__invoke(230) >>Symfony\\Component\\EventDispatcher\\EventDispatcher::callListeners(59) >>Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch(151) >>Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch(154) >>Zikula\\ExtensionsModule\\Helper\\ExtensionHelper::install(339) >>Zikula\\ExtensionsModule\\Controller\\ExtensionController::installAction(157) >>Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw(79) >>Symfony\\Component\\HttpKernel\\HttpKernel::handle(191) >>Symfony\\Component\\HttpKernel\\Kernel::handle(35) >>"} []
[2020-05-12T07:56:16.671927-04:00] zikula.NOTICE: Extension installation complete {"name":"ZikulaLegalModule"} []
```

note that it never does `zikula.INFO: @1 Wait 3`

**Comment by craigh** [comment]
This was one of the "better" runs. Others took more redirects.

```
[2020-05-13T17:51:40.861550-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 1 to 7 [] []
[2020-05-13T17:51:40.876179-04:00] zikula.NOTICE: removed /Applications/MAMP/htdocs/core.git/var/cache/dev/KernelDevContainer.php (and .lock) [] []
[2020-05-13T17:51:41.267783-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:41.268419-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:51:44.696230-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:44.696877-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:51:48.124508-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:48.125133-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:51:51.561749-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:51.562363-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:51:54.982369-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:54.982981-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:51:58.375242-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:51:58.375812-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:52:01.815582-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:52:01.816212-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:52:05.290401-04:00] zikula.ERROR: InstallerCollector did not contain Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:52:05.290985-04:00] zikula.INFO: @2 Wait 3 [] []
[2020-05-13T17:52:20.197767-04:00] zikula.INFO: InstallerCollector found Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:52:20.207815-04:00] zikula.NOTICE: Extension installation begun {"name":"ZikulaLegalModule"} []
[2020-05-13T17:52:20.208340-04:00] zikula.INFO: InstallerCollector found Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:52:20.381813-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 7 to 3 [] []
[2020-05-13T17:52:20.427502-04:00] zikula.NOTICE: Extension installation complete {"name":"ZikulaLegalModule"} []
[2020-05-13T17:52:37.676720-04:00] zikula.NOTICE: Extension deactivating {"name":"ZikulaLegalModule"} []
[2020-05-13T17:52:37.677569-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 3 to 2 [] []
[2020-05-13T17:52:37.692400-04:00] zikula.NOTICE: removed /Applications/MAMP/htdocs/core.git/var/cache/dev/KernelDevContainer.php (and .lock) [] []
[2020-05-13T17:52:42.828493-04:00] zikula.INFO: Changing state of ZikulaLegalModule from 2 to 7 [] []
[2020-05-13T17:52:42.843178-04:00] zikula.NOTICE: removed /Applications/MAMP/htdocs/core.git/var/cache/dev/KernelDevContainer.php (and .lock) [] []
[2020-05-13T17:52:48.246139-04:00] zikula.NOTICE: Extension uninstallation begun {"name":"ZikulaLegalModule"} []
[2020-05-13T17:52:48.247149-04:00] zikula.INFO: InstallerCollector found Zikula\LegalModule\LegalModuleInstaller [] []
[2020-05-13T17:52:48.264267-04:00] zikula.NOTICE: removed /Applications/MAMP/htdocs/core.git/var/cache/dev/KernelDevContainer.php (and .lock) [] []
[2020-05-13T17:52:48.644160-04:00] zikula.NOTICE: Extension uninstallation complete {"name":"ZikulaLegalModule"} []
[2020-05-13T17:52:48.989038-04:00] zikula.NOTICE: removed /Applications/MAMP/htdocs/core.git/var/cache/dev/KernelDevContainer.php (and .lock) [] []
```

**Pull request merged**
