### PR TITLE
refactor to runtime implementations

### PR DESCRIPTION
**Pull request by craigh**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | #4520
| License           | MIT
| Changelog updated | yes

## Description

refactor to runtime implementations

## Todos

- [x] Changelog

### CODE REVIEW

**Review by Guite — APPROVED** [review]

**Comment by Guite** [comment]
Do you intend to continue with further system modules and core bundle, too?

**Comment by craigh** [comment]
> Do you intend to continue with further system modules and core bundle, too?

yes. this is currently incomplete.

**Comment by craigh** [comment]
@Guite - I think this is complete, please take a closer look.

**Review by Guite — APPROVED** [review]
Awesome :-)

**Comment by craigh** [comment]
@Guite, I did not convert RoutesModule. I figured you would be updating the generator.

**Comment by Guite** [comment]
> I figured you would be updating the generator.

Indeed :smile:

**Pull request merged**
