### PR TITLE
attempt to move require.js files into subfolder

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3669 
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
are these files never required for anything? Why do we have them? @Kaik

**Comment by craigh** [comment]
@Guite this probably requires a changelog as it is a BC break if the path changed

**Comment by Guite** [comment]
> are these files never required for anything?
No, afaik they are there for people who may need them.

> requires a changelog
added in https://github.com/zikula/core/commit/56515a73b803ed8ab587eaf599171b8f54e908e7

**Comment by Kaik** [comment]
Roblach Component Installer is installing it by default we do not use them afaik.

**Pull request merged**
