### PR TITLE
Switching order of array, to load remote CSS file first

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | https://github.com/zikula/core/issues/3465
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

## Description

Switching order of array, to load remote CSS file first, when merging.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

### CODE REVIEW

**Comment by craigh** [comment]
I don't know the circumstances in which someone might wish to include any external asset. Couldn't this _cause_ as many problems as it solves? for example what if the external asset was dependent on jQuery (which is loaded later)?

**Comment by shefik** [comment]
This is only switching the load of CSS, not JavaScript. So, jQuery would not be affected.

**Comment by craigh** [comment]
no. It affects both. please review the code.

**Comment by shefik** [comment]
Okay, I only meant to change loading for CSS, not JS.

**Comment by craigh** [comment]
> Okay, I only meant to change loading for CSS, not JS.
OK. update the PR or close it then as this will affect both.

**Comment by Guite** [comment]
ping @shefik

**Pull request closed without merging**
