### PR TITLE
Removed dummy bundles

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #1832 
| Refs tickets      | #4032 
| License           | MIT
| Changelog updated | yes

### CODE REVIEW

**Comment by Guite** [comment]
@craigh I don't see any paths which need amendments. Can you explain which ones you are referring to?

**Comment by craigh** [comment]
try manually clearing your `/web` folder and running `composer install`. See if your site works (e.g. all the assets load properly). If not, you should probably look at (at minimum) these paths:

https://github.com/zikula/core/blob/5771fadd5eae37d5cbca8286ee8ab8e45eff7ac2/src/system/ThemeModule/EventListener/DefaultPageAssetSetterListener.php#L126-L127

https://github.com/zikula/core/blob/46ea02f9675ea65b692410fd52a6380144ba2569/src/lib/Zikula/Composer/LessGenerator.php#L34

**Comment by Guite** [comment]
It all works. Actually no paths really changed...

**Comment by craigh** [comment]
really. that seems impossible. but if you say so 😄

**Comment by Guite** [comment]
Well, the paths are still defined by `components/foo`. The only difference is that we now use these directly and not indirectly through our dummy bundles.

**Pull request merged**
