### PR TITLE
Disabling CSRF Protection

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | https://github.com/zikula/core/issues/3831
| Refs tickets      | -
| License           | MIT
| Changelog updated | yes

## Description
Disabling CSRF protection.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog

### CODE REVIEW

**Comment by Guite** [comment]
@shefik there is still a conflict here. Can you please resolve that so we can merge that PR? thanks!

**Comment by Guite** [comment]
Sorry shefik, you need to rebase again now that I merged #3852

**Comment by shefik** [comment]
@Guite Rebased.

**Comment by Guite** [comment]
It still shows

> Conflicting files
> CHANGELOG-1.5.md

**Comment by shefik** [comment]
@Guite Done.

**Comment by craigh** [comment]
this is too messy to merge.

**Pull request closed without merging**
