### PR TITLE
updated SwiftMailer configuration variable

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | yes
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | #2740 
| Refs tickets      | #999
| License           | MIT
| Doc PR            | 
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
this would need to accommodate upgrades.

**Comment by craigh** [comment]
th reason why travis fails this is because the core has to be changed back to the old value (2.3.*) in composer for the dependency.

**Comment by craigh** [comment]
the build is now passing.

@Guite will you be finishing this PR?

**Comment by Guite** [comment]
Isn't it completed already?

**Comment by Guite** [comment]
oic, you mean upgrades... just a moment

**Comment by Guite** [comment]
Please review again.

**Comment by craigh** [comment]
as far as I can tell, none of your changes actually modify and existing installation during upgrade.

**Comment by Guite** [comment]
Added update code.

**Comment by craigh** [comment]
:+1: slack please.

**Pull request merged**
