### PR TITLE
Allow viewing docs even in upgrade, closes #2530

### LINKED ISSUE #2530: InstallDocs link doesn't work in upgrade
The link just redirects to the same page and doesn't display the doc.
fireshot screen capture 061 - zikula is not upgraded - localhost_tmp_zikula_core-1_4_0_upgrade

### PR DESCRIPTION
**Pull request by cmfcmf**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | ---
| Fixed tickets     | #2530 
| Refs tickets      | ---
| License           | MIT
| Doc PR            | ---
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
travis:
> Your requirements could not be resolved to an installable set of packages.

what?!?!?

otherwise :+1: on the PR

**Comment by craigh** [comment]
I wonder if there is something incompatible between Symfony 2.7.2 and another dependency? refs #2531

**Comment by Guite** [comment]
The travis console says:

```
The requested package zikula/breakit-module could not be found in any version, there may be a typo in the package name.
```

**Comment by craigh** [comment]
maybe it is case-sensitive

in the [repositories area](https://github.com/zikula/core/blob/1.4/composer.json#L132) it is listed as `craigh/Breakit` but it is actually `craigh/BreakIt`

**Comment by craigh** [comment]
odd that it has not errored until now. it hasn't changed

**Comment by craigh** [comment]
also - it isn't `zikula/breakit-module` it is `craigh/breakit-module`

**Comment by craigh** [comment]
maybe it would be simpler to remove it entirely. ;-)

**Comment by cmfcmf** [comment]
@craigh You broke it! :stuck_out_tongue_winking_eye: https://github.com/craigh/BreakIt/commit/cea636bd7cb923bd8ae330855375845735bf0610 Going to fix this.

**Comment by Guite** [comment]
Also this package does not seem to exist on packagist.org yet.

**Comment by cmfcmf** [comment]
@Guite That's why there is https://github.com/zikula/core/blob/1.4/composer.json#L121-L134.

**Comment by cmfcmf** [comment]
I rebased the PRs on the fix and will merge them once Travis finished. Then I'm going to test once again and hopfully all our problems are solved :pray:

**Comment by craigh** [comment]
> I rebased the PRs

I'm not sure that was necessary. I had manually triggered a rebuild on the travis site. It should use the current base which you had already merged the breakout fix, so the change would have included the new fixes. but anyway - it should be fine now I hope.

thanks.

**Comment by cmfcmf** [comment]
> I'm not sure that was necessary.

You are right. :boat:

**Pull request merged**
