### PR TITLE
Removing Support for IE7 and Below

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | yes
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | #2287
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
'deprecating' means leaving it there and telling everyone it will be removed at the next major version.

you are simply *removing* the code. so maybe change the title :smile:

**Comment by shefik** [comment]
@craigh The title has been changed.

**Comment by craigh** [comment]
@cmfcmf what are you thoughts on this? @Guite approves. I am not sure. Was thinking that maybe IE7 should be maintained in all version 1.x but on the fence because IE is generally crap anyway. especially IE <9

**Comment by Guite** [comment]
Bootstrap doesn't support IE7, too, so I doubt things will work flawlessly in a Bootstrap-based theme anyway.

**Comment by craigh** [comment]
@shefik there are a few other IE 7 hacks in the project. can you add the removal of those to this PR as well please?

**Comment by shefik** [comment]
I'll add them.

**Comment by craigh** [comment]
refs #2287

**Comment by cmfcmf** [comment]
I agree with anything IE7 related. BTW this is how http://zikula.org looks like in IE7-Mode of the current IE: 
ie7

**Comment by craigh** [comment]
> I'll add them.
ping @shefik

**Comment by craigh** [comment]
> I'll add them.

ping @shefik

**Comment by shefik** [comment]
@craigh I'm searching for more legacy IE code that can be removed.

**Comment by craigh** [comment]
I don't think you will find much. I only saw one other place (global search for `IE 7`)

also this will need a changeling entry please.

**Comment by shefik** [comment]
@craigh This pull request is ready to be merged.

**Comment by Guite** [comment]
:+1:  from me

**Pull request merged**
