### PR TITLE
use dev mailer by default; show alert if mailer is not enabled

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | #3052 
| Refs tickets      | -
| License           | MIT
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
do not merge this until I have some time

**Comment by craigh** [comment]
so this disables all mail on install? I'm not sure I agree. 😕

**Comment by Guite** [comment]
This does what was suggested in #3052 after I asked about how it should be done.

**Comment by craigh** [comment]
I disagree with this solution. 👎

**Pull request closed without merging**
