### PR TITLE
backported changes from #3196

### PR DESCRIPTION
**Pull request by Guite**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no
| Deprecations?     | no
| Fixed tickets     | -
| Refs tickets      | #3196 
| License           | MIT
| Changelog updated | no

### CODE REVIEW

**Comment by craigh** [comment]
these changes should then be removed from your PR to master.

**Comment by Guite** [comment]
sure.

**Comment by craigh** [comment]
I assume you found no other factory uses like this one then?

**Comment by Guite** [comment]
Yep.

**Pull request merged**
