### PR TITLE
Adding support for umask

### PR DESCRIPTION
**Pull request by shefik**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Deprecations?     | no
| Tests pass?       | yes
| Fixed tickets     | -
| Refs tickets      | -
| License           | MIT
| Doc PR            | -
| Changelog updated | no

### CODE REVIEW

**Comment by cmfcmf** [comment]
I don't think a new setting should be introduced in a legacy config file.

**Comment by shefik** [comment]
@cmfcmf I tested other areas where this particular setting can be placed. However, it only seems to work immediately after the ZikulaKernel. Do you have a suggestion where to place it instead? The particular setting is needed, because the cache files are being created with insufficient permissions. For example, in my server environment, I need the cache files to have "group" permissions, and not just "user" permissions.

**Comment by craigh** [comment]
> I don't think a new setting should be introduced in a legacy config file.

I agree this should not be a legacy feature. 

> Do you have a suggestion where to place it instead? 

probably [the config](https://github.com/zikula/core/blob/1.4/src/app/config/config.yml)

**Comment by shefik** [comment]
@craigh @cmfcmf Updates have been made, to use YAML instead.

**Comment by craigh** [comment]
@shefik have you tested this with a fresh install and upgrade from 13x?

**Comment by shefik** [comment]
@craigh I have not tested with an upgrade, but it does work with a clean install of the latest build.

**Comment by craigh** [comment]
could you please test the upgrade?

**Comment by craigh** [comment]
> could you please test the upgrade?

ping @shefik

**Comment by craigh** [comment]
@shefik. please test the upgrade.

**Comment by craigh** [comment]
this requires a rebase.

**Comment by craigh** [comment]
ping @shefik please rebase this so it can be merged.

**Comment by craigh** [comment]
done in https://github.com/zikula/core/commit/dfb7017aedbe3e3753c09d14999f7081dc44ca08

**Pull request closed without merging**
